{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import System.Exit (exitFailure, exitSuccess)
import Test.HUnit

import Test.Suite.CoreBehavior (coreBehaviorTests)
import Test.Suite.ArchitectureInvariants (architectureInvariantTests)
import Test.Suite.SelfPerspective (selfPerspectiveTests)
import Test.Suite.PerspectiveRegistry (perspectiveRegistryTests)
import Test.Suite.Guardrails (guardrailsTests)
import Test.Suite.KnowledgeTree (knowledgeTreeTests)
import Test.Suite.DialogueDevelopment (dialogueDevelopmentTests)
import Test.Suite.TurnPipelineProtocol (turnPipelineProtocolTests)
import Test.Suite.SemanticCorpus (semanticCorpusTests)
import Test.Suite.LexiconTests (lexiconTests)
import Test.Suite.SelfBlanket (selfBlanketTests)
import Test.Suite.SelfConatus (selfConatusTests)
import Test.Suite.SelfAdjunction (selfAdjunctionTests)
import Test.Suite.SelfField (selfFieldTests)
import Test.Suite.SelfAdaptivePosition (selfAdaptivePositionTests)
import Test.Suite.SelfFamilyTargets (selfFamilyTargetsTests)
import Test.Suite.FMARCore (fmarCoreTests)
import Test.Suite.SelfSalience (selfSalienceTests)
import Test.Suite.SelfDeliberation (selfDeliberationTests)
import Test.Suite.SelfEssence (selfEssenceTests)
import Test.Suite.SelfEssenceCommit (selfEssenceCommitTests)
import Test.Suite.P5Governance (p5GovernanceTests)
import Test.Suite.PhaseM2d (phaseM2dTests)
import Test.Suite.LearningLoop (learningLoopTests)
import Test.Suite.TrainingCycle (trainingCycleTests)
import Test.Suite.TunedConfigLoading (tunedConfigLoadingTests)
import Test.Suite.ReliabilityHardening (reliabilityHardeningTests)
import Test.Suite.M6Witness (m6WitnessTests)
import Test.Suite.M5Regime (m5RegimeTests)
import Test.Suite.SemanticCommitmentCorpus (semanticCommitmentCorpusTests)
import Test.Suite.AuthoritySurface (authoritySurfaceTests)
import Test.Suite.DatalogSafety (datalogSafetyTests)
import Test.Suite.SandboxBoundary (sandboxBoundaryTests)
import Test.Suite.PGFErrorHandling (pgfErrorHandlingTests)
import Test.Suite.StructuredErrors (structuredErrorsTests)
import Test.Suite.MemoryEpisodic (episodicMemoryTests)
import Test.Suite.UserModel (userModelTests)
import Test.Suite.CognitiveSignals (cognitiveSignalsTests)
import Test.Suite.DoubtLoop (doubtLoopTests)
import Test.Suite.AffectModel (affectModelTests)
import Test.Suite.ContentSalience (contentSalienceTests)
import Test.Suite.DerivedInference (derivedInferenceTests)
import Test.Suite.GFParityHarness (gfParityHarnessTests)
import Test.Suite.SemanticContentB3 (semanticContentB3Tests)
import Test.Suite.SemanticRepairB3 (semanticRepairB3Tests)
import Test.Suite.B3MechanicalGateExecution (b3MechanicalGateExecutionTests)
import Test.Suite.RoundTrip (roundTripTests)
import Test.Suite.NativeSQLiteNulls (nativeSQLiteNullsTests)
import Test.Suite.AtomStore (atomStoreTests)
import Test.Suite.PathFinder (pathFinderTests)
import Test.Suite.GeneratedPredicateGate (generatedPredicateGateTests)
import Test.Suite.SubstrateCandidate (substrateCandidateTests)
import Test.Suite.ContentQualityGate (contentQualityGateTests)
import Test.Suite.CorpusTuning (corpusTuningTests)
import Test.Suite.TuningRuntimeIntegration (tuningRuntimeIntegrationTests)
import Test.Suite.DialogueSemanticSelection (dialogueSemanticSelectionTests)
import Test.Suite.BootstrapRecovery (bootstrapRecoveryTests)
import Test.Suite.BootstrapExternalKnowledge (bootstrapExternalKnowledgeTests)
import Test.Suite.OntologyContentSelector (ontologyContentSelectorTests)
import Test.Suite.SurfaceAccumulator (surfaceAccumulatorTests)
import Test.Suite.SurfaceAccumulatorGolden (surfaceAccumulatorGoldenTests)
import Test.Suite.Ontology (ontologyTests)
import Test.Suite.OntologyCategoryClassification (ontologyCategoryClassificationTests)
import Test.Suite.OntologyContentSelector (ontologyContentSelectorTests)
import Test.Suite.Autonomous (autonomousTests)
import Test.Suite.DensityGate (densityGateTests)
import Test.Suite.RuntimeLLMToNetwork (runtimeLLMToNetworkTests)
import Test.Suite.CLIIngest (cliIngestTests)
import Test.Suite.NetworkIngest (networkIngestTests)
import Test.Suite.NetworkTypes (networkTypesTests)
import Test.Suite.NetworkFeedback (networkFeedbackTests)
import Test.Suite.FeedbackLoopEndToEnd (feedbackLoopEndToEndTests)
import Test.Suite.RelationWeightOverlay (relationWeightOverlayTests)
import Test.Suite.SelfPlayRelations (selfPlayRelationsTests)
import Test.Suite.CuratedPredicates (curatedPredicatesTests)
import Test.Suite.VariantC (variantCTests)
import Test.Suite.AtomGraphSeed (atomGraphSeedTests)

main :: IO ()
main = do
  -- TuningRuntimeIntegration must run first: it forces the top-level
  -- 'defaultSalienceWeights' / 'defaultFieldHeuristics' CAFs and verifies
  -- they load tuned config files when present.
  testCounts <- runTestTT $ TestList (tuningRuntimeIntegrationTests ++ coreBehaviorTests ++ architectureInvariantTests ++ selfPerspectiveTests ++ perspectiveRegistryTests ++ guardrailsTests ++ knowledgeTreeTests ++ dialogueDevelopmentTests ++ turnPipelineProtocolTests ++ semanticCorpusTests ++ lexiconTests ++ selfBlanketTests ++ selfConatusTests ++ selfAdjunctionTests ++ selfFieldTests ++ selfAdaptivePositionTests ++ selfFamilyTargetsTests ++ fmarCoreTests ++ selfSalienceTests ++ selfDeliberationTests ++ selfEssenceTests ++ selfEssenceCommitTests ++ p5GovernanceTests ++ phaseM2dTests ++ learningLoopTests ++ trainingCycleTests ++ tunedConfigLoadingTests ++ reliabilityHardeningTests ++ m6WitnessTests ++ m5RegimeTests ++ semanticCommitmentCorpusTests ++ authoritySurfaceTests ++ datalogSafetyTests ++ sandboxBoundaryTests ++ pgfErrorHandlingTests ++ structuredErrorsTests ++ episodicMemoryTests ++ userModelTests ++ cognitiveSignalsTests ++ doubtLoopTests ++ affectModelTests ++ contentSalienceTests ++ derivedInferenceTests ++ gfParityHarnessTests   ++ semanticContentB3Tests ++ semanticRepairB3Tests   ++ b3MechanicalGateExecutionTests ++ [roundTripTests]   ++ nativeSQLiteNullsTests ++ atomStoreTests   ++ pathFinderTests ++ generatedPredicateGateTests ++ substrateCandidateTests ++ contentQualityGateTests ++ corpusTuningTests ++ dialogueSemanticSelectionTests ++ ontologyTests ++ ontologyCategoryClassificationTests ++ ontologyContentSelectorTests ++ autonomousTests ++ densityGateTests ++ runtimeLLMToNetworkTests ++ bootstrapRecoveryTests ++ bootstrapExternalKnowledgeTests ++ surfaceAccumulatorTests ++ surfaceAccumulatorGoldenTests ++ networkIngestTests ++ networkTypesTests ++ networkFeedbackTests ++ feedbackLoopEndToEndTests ++ cliIngestTests ++ selfPlayRelationsTests ++ curatedPredicatesTests ++ variantCTests ++ atomGraphSeedTests ++ relationWeightOverlayTests)
  if errors testCounts + failures testCounts > 0
    then exitFailure
    else exitSuccess
