{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import System.Exit (exitFailure, exitSuccess)
import Test.HUnit

import Test.Suite.CoreBehavior (coreBehaviorTests)
import Test.Suite.ArchitectureInvariants (architectureInvariantTests)
import Test.Suite.SelfPerspective (selfPerspectiveTests)
import Test.Suite.PerspectiveRegistry (perspectiveRegistryTests)
import Test.Suite.Guardrails (guardrailsTests)
import Test.Suite.KnowledgeTree (knowledgeTreeTests)
import Test.Suite.DialogueDevelopment (dialogueDevelopmentTests)
import Test.Suite.TurnPipelineProtocol (turnPipelineProtocolTests)
import Test.Suite.SemanticCorpus (semanticCorpusTests)
import Test.Suite.LexiconTests (lexiconTests)
import Test.Suite.SelfBlanket (selfBlanketTests)
import Test.Suite.SelfConatus (selfConatusTests)
import Test.Suite.SelfAdjunction (selfAdjunctionTests)
import Test.Suite.SelfField (selfFieldTests)
import Test.Suite.SelfAdaptivePosition (selfAdaptivePositionTests)
import Test.Suite.SelfFamilyTargets (selfFamilyTargetsTests)
import Test.Suite.FMARCore (fmarCoreTests)
import Test.Suite.SelfSalience (selfSalienceTests)
import Test.Suite.SelfDeliberation (selfDeliberationTests)
import Test.Suite.SelfEssence (selfEssenceTests)
import Test.Suite.SelfEssenceCommit (selfEssenceCommitTests)
import Test.Suite.P5Governance (p5GovernanceTests)
import Test.Suite.PhaseM2d (phaseM2dTests)
import Test.Suite.LearningLoop (learningLoopTests)
import Test.Suite.TrainingCycle (trainingCycleTests)
import Test.Suite.ReliabilityHardening (reliabilityHardeningTests)
import Test.Suite.M6Witness (m6WitnessTests)
import Test.Suite.M5Regime (m5RegimeTests)
import Test.Suite.SemanticCommitmentCorpus (semanticCommitmentCorpusTests)
import Test.Suite.AuthoritySurface (authoritySurfaceTests)
import Test.Suite.DatalogSafety (datalogSafetyTests)
import Test.Suite.SandboxBoundary (sandboxBoundaryTests)
import Test.Suite.PGFErrorHandling (pgfErrorHandlingTests)
import Test.Suite.StructuredErrors (structuredErrorsTests)
import Test.Suite.MemoryEpisodic (episodicMemoryTests)
import Test.Suite.UserModel (userModelTests)
import Test.Suite.CognitiveSignals (cognitiveSignalsTests)
import Test.Suite.DoubtLoop (doubtLoopTests)
import Test.Suite.AffectModel (affectModelTests)
import Test.Suite.ContentSalience (contentSalienceTests)
import Test.Suite.DerivedInference (derivedInferenceTests)
import Test.Suite.GFParityHarness (gfParityHarnessTests)
import Test.Suite.SemanticContentB3 (semanticContentB3Tests)
import Test.Suite.SemanticRepairB3 (semanticRepairB3Tests)
import Test.Suite.B3MechanicalGateExecution (b3MechanicalGateExecutionTests)
import Test.Suite.RoundTrip (roundTripTests)
import Test.Suite.AtomStore (atomStoreTests)
import Test.Suite.PathFinder (pathFinderTests)

main :: IO ()
main = do
  testCounts <- runTestTT $ TestList (coreBehaviorTests ++ architectureInvariantTests ++ selfPerspectiveTests ++ perspectiveRegistryTests ++ guardrailsTests ++ knowledgeTreeTests ++ dialogueDevelopmentTests ++ turnPipelineProtocolTests ++ semanticCorpusTests ++ lexiconTests ++ selfBlanketTests ++ selfConatusTests ++ selfAdjunctionTests ++ selfFieldTests ++ selfAdaptivePositionTests ++ selfFamilyTargetsTests ++ fmarCoreTests ++ selfSalienceTests ++ selfDeliberationTests ++ selfEssenceTests ++ selfEssenceCommitTests ++ p5GovernanceTests ++ phaseM2dTests ++ learningLoopTests ++ trainingCycleTests ++ reliabilityHardeningTests ++ m6WitnessTests ++ m5RegimeTests ++ semanticCommitmentCorpusTests ++ authoritySurfaceTests ++ datalogSafetyTests ++ sandboxBoundaryTests ++ pgfErrorHandlingTests ++ structuredErrorsTests ++ episodicMemoryTests ++ userModelTests ++ cognitiveSignalsTests ++ doubtLoopTests ++ affectModelTests ++ contentSalienceTests ++ derivedInferenceTests ++ gfParityHarnessTests   ++ semanticContentB3Tests ++ semanticRepairB3Tests   ++ b3MechanicalGateExecutionTests ++ [roundTripTests] ++ atomStoreTests ++ pathFinderTests)
  if errors testCounts + failures testCounts > 0
    then exitFailure
    else exitSuccess
