{-| Core-facing effect boundary and helper operations for runtime-integrated turn execution. -}
module QxFx0.Core.PipelineIO
  ( PipelineRuntimeMode(..)
  , LocalRecoveryPolicy(..)
  , ShadowPolicy(..)
  , ShadowResult(..)
  , PipelineIO
  , TestPipelineConfig(..)
  , defaultTestPipelineConfig
  , mkTestPipelineIO
  , mkReplayPipelineIO
  , pipelineRuntimeMode
  , pipelineRuntimeModeText
  , pipelineShadowPolicy
  , shadowPolicyText
  , pipelineLocalRecoveryPolicy
  , localRecoveryPolicyText
  , scheduleTurnEffects
  , resolveTurnEffect
  , resolveTurnEffects
  , runShadowVerification
  , verifyPipelineAgda
  , savePipelineState
  , checkpointPipelineState
  , resolvePipelineNixPath
  , runPipelineNixCheck
  , modifyPipelineConsciousLoop
  , modifyPipelineIntuition
  , checkPipelineApiHealth
  , pipelineUpdateHistory
  , pipelineParseAuthoritySurface
  ) where

import QxFx0.Core.PipelineIO.Internal
  ( LocalRecoveryPolicy(..)
  , PipelineIO
  , PipelineRuntimeMode(..)
  , ShadowPolicy(..)
  , ShadowResult(..)
  )
import QxFx0.Core.PipelineIO.Operations
  ( checkPipelineApiHealth
    , checkpointPipelineState
    , localRecoveryPolicyText
    , modifyPipelineConsciousLoop
    , modifyPipelineIntuition
    , pipelineLocalRecoveryPolicy
    , pipelineRuntimeModeText
    , pipelineRuntimeMode
    , scheduleTurnEffects
    , pipelineShadowPolicy
    , shadowPolicyText
  , pipelineUpdateHistory
  , pipelineParseAuthoritySurface
  , resolvePipelineNixPath
  , resolveTurnEffect
  , resolveTurnEffects
  , runPipelineNixCheck
  , runShadowVerification
  , savePipelineState
  , verifyPipelineAgda
  )
import QxFx0.Core.PipelineIO.Test
  ( TestPipelineConfig(..)
  , defaultTestPipelineConfig
  , mkTestPipelineIO
  )
import QxFx0.Core.PipelineIO.Replay
  ( mkReplayPipelineIO
  )
