INSERT INTO realization_templates (move_kind, style, role, structure, slots, priority) VALUES
('MoveGroundKnown', 'standard', 'opening', 'Известно, что {nom:topic}.', 'nom:topic', 0.80),
('MoveGroundBasis', 'standard', 'core', 'Основанием служит {gen:topic}.', 'gen:topic', 0.80),
('MoveDefineFrame', 'standard', 'opening', 'Определим {nom:topic} через рамку {gen:frame}.', 'nom:topic,gen:frame', 0.80),
('MoveStateDefinition', 'standard', 'core', '{nom:topic} — это {nom:definition}.', 'nom:topic,nom:definition', 0.80),
('MoveShowContrast', 'standard', 'opening', 'Различие между {nom:left} и {nom:right}.', 'nom:left,nom:right', 0.75),
('MoveStateBoundary', 'standard', 'core', 'Граница {gen:topic} проходит там, где {nom:boundary}.', 'gen:topic,nom:boundary', 0.75),
('MoveReflectMirror', 'standard', 'opening', 'Вы отразили {nom:topic}. Что это значит?', 'nom:topic', 0.75),
('MoveReflectResonate', 'standard', 'core', 'Ваше отражение {gen:topic} резонирует с {ablt:resonance}.', 'gen:topic,ablt:resonance', 0.75),
('MoveDescribeSketch', 'standard', 'opening', 'Представим {nom:topic}.', 'nom:topic', 0.70),
('MovePurposeTeleology', 'standard', 'core', 'Назначение {gen:topic} состоит в {prep:purpose}.', 'gen:topic,prep:purpose', 0.70),
('MoveHypothesizeTest', 'standard', 'opening', 'Гипотеза: может ли {nom:topic} быть {ablt:hypothesis}?', 'nom:topic,ablt:hypothesis', 0.70),
('MoveRepairBridge', 'standard', 'opening', 'Давайте восстановим связь через {acc:bridge}.', 'acc:bridge', 0.80),
('MoveAcknowledgeRupture', 'standard', 'core', 'Я признаю разрыв в {prep:topic}.', 'prep:topic', 0.80),
('MoveContactBridge', 'standard', 'opening', 'Я слышу запрос на контакт о {prep:topic}.', 'prep:topic', 0.80),
('MoveContactReach', 'standard', 'core', 'Протягиваю руку через {acc:topic}.', 'acc:topic', 0.80),
('MoveAnchorStabilize', 'standard', 'opening', 'Опора: {nom:topic} остаётся устойчивой.', 'nom:topic', 0.80),
('MoveClarifyDisambiguate', 'standard', 'opening', 'Уточним: вы имеете в виду {nom:opt1} или {nom:opt2}?', 'nom:opt1,nom:opt2', 0.80),
('MoveDeepenProbe', 'standard', 'core', 'Что стоит за {ablt:topic} глубже всего?', 'ablt:topic', 0.80),
('MoveConfrontChallenge', 'standard', 'opening', 'Возражение: {nom:topic} требует проверки.', 'nom:topic', 0.75),
('MoveNextStep', 'standard', 'opening', 'Следующий шаг: {nom:nextstep}.', 'nom:nextstep', 0.80),
('MoveDefineFrame', 'formal', 'opening', 'Формализуем {acc:topic} в рамке {gen:frame}.', 'acc:topic,gen:frame', 0.65),
('MoveReflectMirror', 'warm', 'opening', 'Я рядом с вашим вопросом о {prep:topic}.', 'prep:topic', 0.65),
('MoveGroundKnown', 'poetic', 'opening', 'Из глубины звучит {nom:topic}.', 'nom:topic', 0.60),
('MoveConfrontChallenge', 'direct', 'opening', 'Не согласен с {ablt:topic}. Почему?', 'ablt:topic', 0.60);
