{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}
{-|
Runtime lexical base: every lemma stores its FULL paradigm.
No suffix heuristics. Lookup is O(log n).

Loaded from resources/morphology/paradigms.json (generated by
scripts/generate_paradigms_pymorphy2.py).
-}
module QxFx0.Semantic.Lexicon.RuntimeParadigms
  ( ParadigmEntry(..)
  , RuntimeParadigms(..)
  , loadRuntimeParadigms
  , loadDefaultRuntimeParadigms
   , emptyRuntimeParadigms
   , testRuntimeParadigms
  , NounCase(..)
  , Number(..)
  , Gender(..)
  , VerbForm(..)
  , AdjectiveForm(..)
  , lookupNounForm
  , lookupNounFormOr
  , lookupVerbForm
  , lookupVerbFormOr
  , lookupAdjectiveForm
  , lookupAdjectiveFormOr
  , lookupAdverbForm
  , lookupExpression
  , lookupMetaphor
  , lemmaGender
  , lemmaPos
  , guessGender
  , guessGenderOr
  , hasParadigm
  , allParadigmLemmas
  , inferGenitive
  , inferPrepositional
  , inferAccusative
  , inferInstrumental
  , inferDative
  ) where

import Control.Applicative ((<|>))
import Data.Aeson (FromJSON(..), eitherDecodeStrict, genericParseJSON, defaultOptions, fieldLabelModifier)
import Data.Char (toLower)
import Data.Maybe (fromMaybe, listToMaybe)
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as M
import Data.Text (Text)
import qualified Data.Text as T
import GHC.Generics (Generic)
import qualified Data.ByteString as BS
import System.Directory (doesFileExist)
import System.IO (hPutStrLn, stderr)
import System.IO.Unsafe (unsafePerformIO)
import Control.DeepSeq (NFData)

--------------------------------------------------------------------------------
-- Types
--------------------------------------------------------------------------------

data ParadigmEntry = ParadigmEntry
  { pePos     :: !Text
  , peGender  :: !(Maybe Text)
  , peAnimacy :: !(Maybe Text)
  , peAspect  :: !(Maybe Text)
  , peTransitivity :: !(Maybe Text)
  , peForms   :: !(Map Text Text)
  } deriving stock (Eq, Show, Generic)
    deriving anyclass (NFData)

instance FromJSON ParadigmEntry where
  parseJSON = genericParseJSON defaultOptions
    { fieldLabelModifier = \lbl -> case lbl of
        ('p':'e':rest) -> map toLower rest
        _              -> map toLower lbl
    }

data RuntimeParadigms = RuntimeParadigms
  { rpMap        :: !(Map Text ParadigmEntry)
  , rpExceptions :: !(Map Text ParadigmEntry)
  } deriving stock (Eq, Show)

--------------------------------------------------------------------------------
-- Load
--------------------------------------------------------------------------------

loadRuntimeParadigms :: BS.ByteString -> Either String RuntimeParadigms
loadRuntimeParadigms bs = do
  paradigms <- eitherDecodeStrict bs
  pure RuntimeParadigms { rpMap = paradigms, rpExceptions = mempty }

emptyRuntimeParadigms :: RuntimeParadigms
emptyRuntimeParadigms = RuntimeParadigms mempty mempty

-- | Test helper: loaded paradigms for test suites. Not for production use.
testRuntimeParadigms :: RuntimeParadigms
testRuntimeParadigms = unsafePerformIO loadDefaultRuntimeParadigms
{-# NOINLINE testRuntimeParadigms #-}

-- | Load paradigms + exceptions from default paths. Pure IO — no global cache.
loadDefaultRuntimeParadigms :: IO RuntimeParadigms
loadDefaultRuntimeParadigms = do
  paradigms <- loadFile "resources/morphology/paradigms.json" "paradigms"
  exceptions <- loadFile "resources/morphology/exceptions.json" "exceptions"
  pure RuntimeParadigms { rpMap = paradigms, rpExceptions = exceptions }
  where
    loadFile path label = do
      exists <- doesFileExist path
      if not exists
        then do
          hPutStrLn stderr $ "[RuntimeParadigms] " <> label <> " file not found: " <> path
          pure mempty
        else do
          bs <- BS.readFile path
          case eitherDecodeStrict bs of
            Left err -> do
              hPutStrLn stderr $ "[RuntimeParadigms] " <> label <> " parse error: " <> err
              pure mempty
            Right mp -> pure (mp :: Map Text ParadigmEntry)

--------------------------------------------------------------------------------
-- Noun lookup
--------------------------------------------------------------------------------

data NounCase = Nom | Gen | Dat | Acc | Ins | Loc
  deriving stock (Eq, Ord, Show, Bounded, Enum)

data Number = Sg | Pl
  deriving stock (Eq, Ord, Show, Bounded, Enum)

nounCaseKey :: NounCase -> Number -> Text
nounCaseKey c n = T.pack (show c <> show n)

lookupNounForm :: RuntimeParadigms -> Text -> NounCase -> Number -> Maybe Text
lookupNounForm rp lemma case_ number =
  lookupInMap (rpMap rp) <|> lookupInMap (rpExceptions rp)
  where
    lookupInMap mp = do
      entry <- M.lookup lemma mp
      guard (pePos entry == "Noun")
      case (case_, peGender entry, peAnimacy entry) of
        (Acc, Just "masc", Just "anim") ->
          M.lookup (nounCaseKey Gen number) (peForms entry)
        (Acc, Just "masc", Just "inan") ->
          M.lookup (nounCaseKey Nom number) (peForms entry)
        _ ->
          M.lookup (nounCaseKey case_ number) (peForms entry)

lookupNounFormOr :: RuntimeParadigms -> Text -> NounCase -> Number -> Text -> Text
lookupNounFormOr rp lemma case_ number fallback =
  fromMaybe fallback (lookupNounForm rp lemma case_ number)

lemmaGender :: RuntimeParadigms -> Text -> Maybe Text
lemmaGender rp lemma = lookupInMap (rpMap rp) <|> lookupInMap (rpExceptions rp)
  where
    lookupInMap mp = do
      entry <- M.lookup lemma mp
      peGender entry

lemmaPos :: RuntimeParadigms -> Text -> Maybe Text
lemmaPos rp lemma = lookupInMap (rpMap rp) <|> lookupInMap (rpExceptions rp)
  where
    lookupInMap mp = pePos <$> M.lookup lemma mp

--------------------------------------------------------------------------------
-- Verb lookup
--------------------------------------------------------------------------------

data VerbForm
  = Inf
  | PastSgMasc | PastSgFem | PastSgNeut | PastPl
  | Pres1Sg | Pres2Sg | Pres3Sg | Pres1Pl | Pres2Pl | Pres3Pl
  | Fut1Sg | Fut2Sg | Fut3Sg | Fut1Pl | Fut2Pl | Fut3Pl
  | ImpSg | ImpPl
  deriving stock (Eq, Ord, Show, Bounded, Enum)

verbFormKey :: VerbForm -> Text
verbFormKey = T.pack . show

lookupVerbForm :: RuntimeParadigms -> Text -> VerbForm -> Maybe Text
lookupVerbForm rp lemma form = lookupInMap (rpMap rp) <|> lookupInMap (rpExceptions rp)
  where
    lookupInMap mp = do
      entry <- M.lookup lemma mp
      guard (pePos entry == "Verb")
      M.lookup (verbFormKey form) (peForms entry)

lookupVerbFormOr :: RuntimeParadigms -> Text -> VerbForm -> Text -> Text
lookupVerbFormOr rp lemma form fallback =
  fromMaybe fallback (lookupVerbForm rp lemma form)

--------------------------------------------------------------------------------
-- Adjective lookup
--------------------------------------------------------------------------------

data AdjectiveForm
  = AdjFull NounCase Number (Maybe Gender)   -- full forms
  | AdjShort Gender                           -- short forms
  deriving stock (Eq, Ord, Show)

data Gender = Masc | Femn | Neut
  deriving stock (Eq, Ord, Bounded, Enum)

instance Show Gender where
  show Masc = "Masc"
  show Femn = "Fem"
  show Neut = "Neut"

adjectiveFormKey :: AdjectiveForm -> Text
adjectiveFormKey (AdjFull c Sg (Just g))  = T.pack (show c <> "Sg" <> show g)
adjectiveFormKey (AdjFull c Pl _)         = T.pack (show c <> "Pl")
adjectiveFormKey (AdjFull c Sg Nothing)   = T.pack (show c <> "Sg")
adjectiveFormKey (AdjShort g)             = T.pack ("Short" <> show g)

lookupAdjectiveForm :: RuntimeParadigms -> Text -> AdjectiveForm -> Maybe Text
lookupAdjectiveForm rp lemma form = lookupInMap (rpMap rp) <|> lookupInMap (rpExceptions rp)
  where
    lookupInMap mp = do
      entry <- M.lookup lemma mp
      guard (pePos entry == "Adjective")
      M.lookup (adjectiveFormKey form) (peForms entry)

lookupAdjectiveFormOr :: RuntimeParadigms -> Text -> AdjectiveForm -> Text -> Text
lookupAdjectiveFormOr rp lemma form fallback =
  fromMaybe fallback (lookupAdjectiveForm rp lemma form)

---------------------------------------------------------------------------------
--- Adverb lookup
---------------------------------------------------------------------------------

lookupAdverbForm :: RuntimeParadigms -> Text -> Maybe Text
lookupAdverbForm rp lemma = lookupInMap (rpMap rp) <|> lookupInMap (rpExceptions rp)
  where
    lookupInMap mp = do
      entry <- M.lookup lemma mp
      guard (pePos entry == "Adverb")
      M.lookup "Base" (peForms entry)

lookupExpression :: RuntimeParadigms -> Text -> Maybe Text
lookupExpression rp lemma = do
  entry <- M.lookup lemma (rpMap rp)
  guard (pePos entry == "Expression")
  M.lookup "Base" (peForms entry)

lookupMetaphor :: RuntimeParadigms -> Text -> Maybe Text -> Maybe (Text, Text)
lookupMetaphor rp targetKeyword _mbase =
  let matches = filter (\(_, entry) -> pePos entry == "Metaphor" &&
        M.lookup "Target" (peForms entry) == Just targetKeyword) (M.toList (rpMap rp))
  in case matches of
       (k, entry) : _ ->
         case (M.lookup "Base" (peForms entry), M.lookup "Source" (peForms entry)) of
           (Just b, Just s) -> Just (b, s)
           _                -> Just (k, "образ")
       [] -> Nothing

--------------------------------------------------------------------------------
-- Misc
--------------------------------------------------------------------------------

hasParadigm :: RuntimeParadigms -> Text -> Bool
hasParadigm rp lemma = M.member lemma (rpMap rp) || M.member lemma (rpExceptions rp)

allParadigmLemmas :: RuntimeParadigms -> [Text]
allParadigmLemmas rp = M.keys (rpMap rp) ++ M.keys (rpExceptions rp)

-- | Guess grammatical gender using the runtime paradigms database,
-- falling back to suffix heuristics when the lemma is absent.
guessGender :: RuntimeParadigms -> Text -> Maybe Gender
guessGender rp t =
  case lemmaGender rp t of
    Just "femn" -> Just Femn
    Just "neut" -> Just Neut
    Just _      -> Just Masc
    Nothing     ->
      let w = T.toLower t
      in if T.isSuffixOf "а" w || T.isSuffixOf "я" w
           then Just Femn
         else if T.isSuffixOf "о" w || T.isSuffixOf "е" w
           then Just Neut
         else Just Masc

-- | Like 'guessGender' but returns a default instead of 'Nothing'.
guessGenderOr :: RuntimeParadigms -> Gender -> Text -> Gender
guessGenderOr rp def t =
  case lemmaGender rp t of
    Just "femn" -> Femn
    Just "neut" -> Neut
    Just _      -> Masc
    Nothing     ->
      let w = T.toLower t
      in if T.isSuffixOf "а" w || T.isSuffixOf "я" w
           then Femn
         else if T.isSuffixOf "о" w || T.isSuffixOf "е" w
           then Neut
         else def

inferGenitive :: RuntimeParadigms -> Text -> Number -> Maybe Text
inferGenitive rp lemma = inferNounForm rp lemma Gen

inferPrepositional :: RuntimeParadigms -> Text -> Number -> Maybe Text
inferPrepositional rp lemma = inferNounForm rp lemma Loc

inferAccusative :: RuntimeParadigms -> Text -> Number -> Maybe Text
inferAccusative rp lemma = inferNounForm rp lemma Acc

inferInstrumental :: RuntimeParadigms -> Text -> Number -> Maybe Text
inferInstrumental rp lemma = inferNounForm rp lemma Ins

inferDative :: RuntimeParadigms -> Text -> Number -> Maybe Text
inferDative rp lemma = inferNounForm rp lemma Dat

inferNounForm :: RuntimeParadigms -> Text -> NounCase -> Number -> Maybe Text
inferNounForm rp lemma targetCase number =
  let w = T.unpack (T.toLower lemma)
      g = guessGender rp lemma
      animacy = peAnimacy <$> M.lookup lemma (rpMap rp)
  in case (g, w) of
       (_, [])   -> Nothing
       (_, [_])  -> Nothing
       (Just Masc, cs) -> inferMasc cs animacy
       (Just Femn, cs) -> inferFemn cs
       (Just Neut, cs) -> inferNeut cs
       (_, _)     -> Nothing
     where
       safeLast cs = if null cs then Nothing else Just (cs !! (length cs - 1))
       safeInit cs = if null cs then [] else take (length cs - 1) cs
       safeLastEq cs c = case safeLast cs of Just c' -> c' == c; Nothing -> False
       isConsStem cs = not (null cs) &&
                       case safeLast cs of
                         Just l  -> l `notElem` ("аеёиоуыэюяьй" :: String)
                         Nothing -> False
       afterVelarOrSibilant s = case safeLast s of
         Just c  -> c `elem` ("кгхжшчщ" :: String)
         Nothing -> False
       decl base (sgG,sgD,sgA_anim,sgA_inan,sgI,sgL) (plG,plD,plA_anim,plA_inan,plI,plL) =
         let animacyLocal = case M.lookup lemma (rpMap rp) of
               Just entry -> peAnimacy entry
               Nothing    -> Nothing
             (sgA, plA) = case animacyLocal of
               Just "anim" -> (sgA_anim, plA_anim)
               Just "inan" -> (sgA_inan, plA_inan)
               _           -> (sgA_inan, plA_inan)  -- default to inanimate
         in case (number, targetCase) of
           (Sg, Gen) -> Just $ T.pack base <> T.pack sgG
           (Sg, Dat) -> Just $ T.pack base <> T.pack sgD
           (Sg, Acc) -> Just $ T.pack base <> T.pack sgA
           (Sg, Ins) -> Just $ T.pack base <> T.pack sgI
           (Sg, Loc) -> Just $ T.pack base <> T.pack sgL
           (Pl, Gen) -> Just $ T.pack base <> T.pack plG
           (Pl, Dat) -> Just $ T.pack base <> T.pack plD
           (Pl, Acc) -> Just $ T.pack base <> T.pack plA
           (Pl, Ins) -> Just $ T.pack base <> T.pack plI
           (Pl, Loc) -> Just $ T.pack base <> T.pack plL
           _         -> Nothing
       inferMasc cs mAnim
         | isConsStem cs =
             let plNom = if afterVelarOrSibilant cs then cs <> "и" else cs <> "ы"
                 plGen = if afterVelarOrSibilant cs then cs <> "ей" else cs <> "ов"
             in decl cs ("а","у","а",cs,"ом","е") (plGen,"ам",plGen,plNom,"ами","ах")
         | safeLastEq cs 'й' =
             let b = safeInit cs
             in decl b ("я","ю","я",cs,"ем","е") ("ев","ям","ев",b<>"и","ями","ях")
         | safeLastEq cs 'ь' =
             let b = safeInit cs
             in decl b ("я","ю","я",cs,"ём","и") ("ей","ям","ей",b<>"и","ями","ях")
         | otherwise = Nothing
       inferFemn cs
         | safeLastEq cs 'а' =
             let b = safeInit cs
                 yOrI = if afterVelarOrSibilant b then "и" else "ы"
             in case (number, targetCase) of
                  (Sg, Gen) -> Just $ T.pack b <> T.pack yOrI
                  (Sg, Dat) -> Just $ T.pack b <> "е"
                  (Sg, Acc) -> Just $ T.pack b <> "у"
                  (Sg, Ins) -> Just $ T.pack b <> "ой"
                  (Sg, Loc) -> Just $ T.pack b <> "е"
                  _         -> Nothing
         | safeLastEq cs 'я' =
             let b = safeInit cs
             in case (number, targetCase) of
                  (Sg, Gen) -> Just $ T.pack b <> "и"
                  (Sg, Dat) -> Just $ T.pack b <> "е"
                  (Sg, Acc) -> Just $ T.pack b <> "ю"
                  (Sg, Ins) -> Just $ T.pack b <> "ей"
                  (Sg, Loc) -> Just $ T.pack b <> "е"
                  _         -> Nothing
         | safeLastEq cs 'ь' =
             let b = safeInit cs
             in case (number, targetCase) of
                  (Sg, Gen) -> Just $ T.pack b <> "и"
                  (Sg, Dat) -> Just $ T.pack b <> "и"
                  (Sg, Acc) -> Just $ T.pack b <> "ь"
                  (Sg, Ins) -> Just $ T.pack b <> "ью"
                  (Sg, Loc) -> Just $ T.pack b <> "и"
                  _         -> Nothing
         | otherwise = Nothing
       inferNeut cs
         | safeLastEq cs 'о' =
             let b = safeInit cs
             in case (number, targetCase) of
                  (Sg, Gen) -> Just $ T.pack b <> "а"
                  (Sg, Dat) -> Just $ T.pack b <> "у"
                  (Sg, Acc) -> Just $ T.pack cs
                  (Sg, Ins) -> Just $ T.pack b <> "ом"
                  (Sg, Loc) -> Just $ T.pack b <> "е"
                  _         -> Nothing
         | safeLastEq cs 'е' =
             let b = safeInit cs
                 isIye = length cs >= 3 && cs !! (length cs - 2) == 'и'
             in if isIye
                then let ib = take (length cs - 2) cs
                     in case (number, targetCase) of
                          (Sg, Gen) -> Just $ T.pack ib <> "ия"
                          (Sg, Dat) -> Just $ T.pack ib <> "ию"
                          (Sg, Acc) -> Just $ T.pack cs
                          (Sg, Ins) -> Just $ T.pack ib <> "ием"
                          (Sg, Loc) -> Just $ T.pack ib <> "ии"
                          (Pl, Gen) -> Just $ T.pack ib <> "ий"
                          (Pl, Dat) -> Just $ T.pack ib <> "иям"
                          (Pl, Acc) -> Just $ T.pack ib <> "ия"
                          (Pl, Ins) -> Just $ T.pack ib <> "иями"
                          (Pl, Loc) -> Just $ T.pack ib <> "иях"
                          _         -> Nothing
                else case (number, targetCase) of
                       (Sg, Gen) -> Just $ T.pack b <> "я"
                       (Sg, Dat) -> Just $ T.pack b <> "ю"
                       (Sg, Acc) -> Just $ T.pack cs
                       (Sg, Ins) -> Just $ T.pack b <> "ем"
                       (Sg, Loc) -> Just $ T.pack b <> "е"
                       _         -> Nothing
         | otherwise = Nothing

guard :: Bool -> Maybe ()
guard True  = Just ()
guard False = Nothing
