{-# OPTIONS --without-K #-}

module LexiconData where

-- AUTO-GENERATED by scripts/export_lexicon.py from spec/sql/lexicon.
-- Canonical direction: SQL -> Agda (do not edit manually).

open import Agda.Builtin.Nat using (Nat)
open import Agda.Builtin.String using (String)
open import Agda.Builtin.Equality using (_≡_; refl)

data Lemma : Set where
  absurd_N : Lemma
  avtonomiya_N : Lemma
  agentnost_N : Lemma
  aksioma_N : Lemma
  antitezis_N : Lemma
  argument_N : Lemma
  bol_N : Lemma
  validnost_N : Lemma
  veroyatnost_N : Lemma
  vechnost_N : Lemma
  vina_N : Lemma
  vozmozhnost_N : Lemma
  volya_N : Lemma
  vopros_N : Lemma
  vremya_N : Lemma
  vybor_N : Lemma
  vyvod_N : Lemma
  vyvodimost_N : Lemma
  vyskazyvanie_N : Lemma
  gipoteza_N : Lemma
  gnev_N : Lemma
  gordost_N : Lemma
  granitsa_N : Lemma
  delat_V : Lemma
  definitsiya_N : Lemma
  dialog_N : Lemma
  distinktsiya_N : Lemma
  doverie_N : Lemma
  dovod_N : Lemma
  dokazatelstvo_N : Lemma
  dolg_N : Lemma
  dopushchenie_N : Lemma
  dostatochnost_N : Lemma
  dostovernost_N : Lemma
  zhizn_N : Lemma
  zadacha_N : Lemma
  zaklyuchenie_N : Lemma
  zapret_N : Lemma
  znat_V : Lemma
  identichnost_N : Lemma
  illyuziya_N : Lemma
  implikatsiya_N : Lemma
  interpretatsiya_N : Lemma
  inferentsiya_N : Lemma
  isklyuchenie_N : Lemma
  istina_N : Lemma
  istinnost_N : Lemma
  kvantor_N : Lemma
  kontakt_N : Lemma
  kontrprimer_N : Lemma
  konflikt_N : Lemma
  konfrontatsiya_N : Lemma
  korollarij_N : Lemma
  korrektnost_N : Lemma
  kriterij_N : Lemma
  lemma_N : Lemma
  logika_N : Lemma
  lozh_N : Lemma
  lyubov_N : Lemma
  modalnost_N : Lemma
  molchanie_N : Lemma
  myslit_V : Lemma
  nadezhda_N : Lemma
  nadezhnost_N : Lemma
  naznachenie_N : Lemma
  neobhodimost_N : Lemma
  neprotivorechivost_N : Lemma
  nesovmestimost_N : Lemma
  nichto_N : Lemma
  obida_N : Lemma
  obosnovanie_N : Lemma
  obyasnenie_N : Lemma
  obyazannost_N : Lemma
  obyazatelstvo_N : Lemma
  ogranichenie_N : Lemma
  odinochestvo_N : Lemma
  opisanie_N : Lemma
  opredelenie_N : Lemma
  oproverzhenie_N : Lemma
  osnovanie_N : Lemma
  osnovyvat_V : Lemma
  otvet_N : Lemma
  otvetstvennost_N : Lemma
  otrazhenie_N : Lemma
  oshibka_N : Lemma
  pamyat_N : Lemma
  pozitsiya_N : Lemma
  ponimanie_N : Lemma
  ponimat_V : Lemma
  ponyatie_N : Lemma
  posylka_N : Lemma
  pravda_N : Lemma
  pravo_N : Lemma
  predpolozhenie_N : Lemma
  predposylka_N : Lemma
  prinuzhdenie_N : Lemma
  prisutstvie_N : Lemma
  prichina_N : Lemma
  proverka_N : Lemma
  proniknut_V : Lemma
  protivorechie_N : Lemma
  pustota_N : Lemma
  ravnosilnost_N : Lemma
  radost_N : Lemma
  razgranichenie_N : Lemma
  razlichat_V : Lemma
  razlichie_N : Lemma
  raznitsa_N : Lemma
  razreshenie_N : Lemma
  razum_N : Lemma
  rakurs_N : Lemma
  remont_N : Lemma
  reshenie_N : Lemma
  svidetelstvo_N : Lemma
  svoboda_N : Lemma
  sillogizm_N : Lemma
  skazat_V : Lemma
  sledstvie_N : Lemma
  smert_N : Lemma
  smirenie_N : Lemma
  smysl_N : Lemma
  soglasie_N : Lemma
  soglasovannost_N : Lemma
  soznanie_N : Lemma
  somnenie_N : Lemma
  sposobnost_N : Lemma
  spravedlivost_N : Lemma
  stradanie_N : Lemma
  strah_N : Lemma
  styd_N : Lemma
  sudba_N : Lemma
  suzhdenie_N : Lemma
  sushchestvovanie_N : Lemma
  sushchestvovat_V : Lemma
  tezis_N : Lemma
  telo_N : Lemma
  teorema_N : Lemma
  termin_N : Lemma
  toska_N : Lemma
  trevoga_N : Lemma
  uslovie_N : Lemma
  utverzhdenie_N : Lemma
  utochnyat_V : Lemma
  utrata_N : Lemma
  uhod_N : Lemma
  fakt_N : Lemma
  filosofiya_N : Lemma
  hrupkost_N : Lemma
  tsel_N : Lemma
  tsifra_N : Lemma
  chestnost_N : Lemma
  ekvivalentsiya_N : Lemma
  eksplikatsiya_N : Lemma
  entejlment_N : Lemma
  yazyk_N : Lemma
  yakor_N : Lemma

lemmaNominative : Lemma → String
lemmaNominative absurd_N = "абсурд"
lemmaNominative avtonomiya_N = "автономия"
lemmaNominative agentnost_N = "агентность"
lemmaNominative aksioma_N = "аксиома"
lemmaNominative antitezis_N = "антитезис"
lemmaNominative argument_N = "аргумент"
lemmaNominative bol_N = "боль"
lemmaNominative validnost_N = "валидность"
lemmaNominative veroyatnost_N = "вероятность"
lemmaNominative vechnost_N = "вечность"
lemmaNominative vina_N = "вина"
lemmaNominative vozmozhnost_N = "возможность"
lemmaNominative volya_N = "воля"
lemmaNominative vopros_N = "вопрос"
lemmaNominative vremya_N = "время"
lemmaNominative vybor_N = "выбор"
lemmaNominative vyvod_N = "вывод"
lemmaNominative vyvodimost_N = "выводимость"
lemmaNominative vyskazyvanie_N = "высказывание"
lemmaNominative gipoteza_N = "гипотеза"
lemmaNominative gnev_N = "гнев"
lemmaNominative gordost_N = "гордость"
lemmaNominative granitsa_N = "граница"
lemmaNominative delat_V = "делать"
lemmaNominative definitsiya_N = "дефиниция"
lemmaNominative dialog_N = "диалог"
lemmaNominative distinktsiya_N = "дистинкция"
lemmaNominative doverie_N = "доверие"
lemmaNominative dovod_N = "довод"
lemmaNominative dokazatelstvo_N = "доказательство"
lemmaNominative dolg_N = "долг"
lemmaNominative dopushchenie_N = "допущение"
lemmaNominative dostatochnost_N = "достаточность"
lemmaNominative dostovernost_N = "достоверность"
lemmaNominative zhizn_N = "жизнь"
lemmaNominative zadacha_N = "задача"
lemmaNominative zaklyuchenie_N = "заключение"
lemmaNominative zapret_N = "запрет"
lemmaNominative znat_V = "знать"
lemmaNominative identichnost_N = "идентичность"
lemmaNominative illyuziya_N = "иллюзия"
lemmaNominative implikatsiya_N = "импликация"
lemmaNominative interpretatsiya_N = "интерпретация"
lemmaNominative inferentsiya_N = "инференция"
lemmaNominative isklyuchenie_N = "исключение"
lemmaNominative istina_N = "истина"
lemmaNominative istinnost_N = "истинность"
lemmaNominative kvantor_N = "квантор"
lemmaNominative kontakt_N = "контакт"
lemmaNominative kontrprimer_N = "контрпример"
lemmaNominative konflikt_N = "конфликт"
lemmaNominative konfrontatsiya_N = "конфронтация"
lemmaNominative korollarij_N = "королларий"
lemmaNominative korrektnost_N = "корректность"
lemmaNominative kriterij_N = "критерий"
lemmaNominative lemma_N = "лемма"
lemmaNominative logika_N = "логика"
lemmaNominative lozh_N = "ложь"
lemmaNominative lyubov_N = "любовь"
lemmaNominative modalnost_N = "модальность"
lemmaNominative molchanie_N = "молчание"
lemmaNominative myslit_V = "мыслить"
lemmaNominative nadezhda_N = "надежда"
lemmaNominative nadezhnost_N = "надежность"
lemmaNominative naznachenie_N = "назначение"
lemmaNominative neobhodimost_N = "необходимость"
lemmaNominative neprotivorechivost_N = "непротиворечивость"
lemmaNominative nesovmestimost_N = "несовместимость"
lemmaNominative nichto_N = "ничто"
lemmaNominative obida_N = "обида"
lemmaNominative obosnovanie_N = "обоснование"
lemmaNominative obyasnenie_N = "объяснение"
lemmaNominative obyazannost_N = "обязанность"
lemmaNominative obyazatelstvo_N = "обязательство"
lemmaNominative ogranichenie_N = "ограничение"
lemmaNominative odinochestvo_N = "одиночество"
lemmaNominative opisanie_N = "описание"
lemmaNominative opredelenie_N = "определение"
lemmaNominative oproverzhenie_N = "опровержение"
lemmaNominative osnovanie_N = "основание"
lemmaNominative osnovyvat_V = "основывать"
lemmaNominative otvet_N = "ответ"
lemmaNominative otvetstvennost_N = "ответственность"
lemmaNominative otrazhenie_N = "отражение"
lemmaNominative oshibka_N = "ошибка"
lemmaNominative pamyat_N = "память"
lemmaNominative pozitsiya_N = "позиция"
lemmaNominative ponimanie_N = "понимание"
lemmaNominative ponimat_V = "понимать"
lemmaNominative ponyatie_N = "понятие"
lemmaNominative posylka_N = "посылка"
lemmaNominative pravda_N = "правда"
lemmaNominative pravo_N = "право"
lemmaNominative predpolozhenie_N = "предположение"
lemmaNominative predposylka_N = "предпосылка"
lemmaNominative prinuzhdenie_N = "принуждение"
lemmaNominative prisutstvie_N = "присутствие"
lemmaNominative prichina_N = "причина"
lemmaNominative proverka_N = "проверка"
lemmaNominative proniknut_V = "проникнуть"
lemmaNominative protivorechie_N = "противоречие"
lemmaNominative pustota_N = "пустота"
lemmaNominative ravnosilnost_N = "равносильность"
lemmaNominative radost_N = "радость"
lemmaNominative razgranichenie_N = "разграничение"
lemmaNominative razlichat_V = "различать"
lemmaNominative razlichie_N = "различие"
lemmaNominative raznitsa_N = "разница"
lemmaNominative razreshenie_N = "разрешение"
lemmaNominative razum_N = "разум"
lemmaNominative rakurs_N = "ракурс"
lemmaNominative remont_N = "ремонт"
lemmaNominative reshenie_N = "решение"
lemmaNominative svidetelstvo_N = "свидетельство"
lemmaNominative svoboda_N = "свобода"
lemmaNominative sillogizm_N = "силлогизм"
lemmaNominative skazat_V = "сказать"
lemmaNominative sledstvie_N = "следствие"
lemmaNominative smert_N = "смерть"
lemmaNominative smirenie_N = "смирение"
lemmaNominative smysl_N = "смысл"
lemmaNominative soglasie_N = "согласие"
lemmaNominative soglasovannost_N = "согласованность"
lemmaNominative soznanie_N = "сознание"
lemmaNominative somnenie_N = "сомнение"
lemmaNominative sposobnost_N = "способность"
lemmaNominative spravedlivost_N = "справедливость"
lemmaNominative stradanie_N = "страдание"
lemmaNominative strah_N = "страх"
lemmaNominative styd_N = "стыд"
lemmaNominative sudba_N = "судьба"
lemmaNominative suzhdenie_N = "суждение"
lemmaNominative sushchestvovanie_N = "существование"
lemmaNominative sushchestvovat_V = "существовать"
lemmaNominative tezis_N = "тезис"
lemmaNominative telo_N = "тело"
lemmaNominative teorema_N = "теорема"
lemmaNominative termin_N = "термин"
lemmaNominative toska_N = "тоска"
lemmaNominative trevoga_N = "тревога"
lemmaNominative uslovie_N = "условие"
lemmaNominative utverzhdenie_N = "утверждение"
lemmaNominative utochnyat_V = "уточнять"
lemmaNominative utrata_N = "утрата"
lemmaNominative uhod_N = "уход"
lemmaNominative fakt_N = "факт"
lemmaNominative filosofiya_N = "философия"
lemmaNominative hrupkost_N = "хрупкость"
lemmaNominative tsel_N = "цель"
lemmaNominative tsifra_N = "цифра"
lemmaNominative chestnost_N = "честность"
lemmaNominative ekvivalentsiya_N = "эквиваленция"
lemmaNominative eksplikatsiya_N = "экспликация"
lemmaNominative entejlment_N = "энтейлмент"
lemmaNominative yazyk_N = "язык"
lemmaNominative yakor_N = "якорь"

lemmaGenitive : Lemma → String
lemmaGenitive absurd_N = "абсурда"
lemmaGenitive avtonomiya_N = "автономии"
lemmaGenitive agentnost_N = "агентности"
lemmaGenitive aksioma_N = "аксиомы"
lemmaGenitive antitezis_N = "антитезиса"
lemmaGenitive argument_N = "аргумента"
lemmaGenitive bol_N = "боли"
lemmaGenitive validnost_N = "валидности"
lemmaGenitive veroyatnost_N = "вероятности"
lemmaGenitive vechnost_N = "вечности"
lemmaGenitive vina_N = "вины"
lemmaGenitive vozmozhnost_N = "возможности"
lemmaGenitive volya_N = "воли"
lemmaGenitive vopros_N = "вопроса"
lemmaGenitive vremya_N = "времени"
lemmaGenitive vybor_N = "выбора"
lemmaGenitive vyvod_N = "вывода"
lemmaGenitive vyvodimost_N = "выводимости"
lemmaGenitive vyskazyvanie_N = "высказывания"
lemmaGenitive gipoteza_N = "гипотезы"
lemmaGenitive gnev_N = "гнева"
lemmaGenitive gordost_N = "гордости"
lemmaGenitive granitsa_N = "границы"
lemmaGenitive delat_V = "делать"
lemmaGenitive definitsiya_N = "дефиниции"
lemmaGenitive dialog_N = "диалога"
lemmaGenitive distinktsiya_N = "дистинкции"
lemmaGenitive doverie_N = "доверия"
lemmaGenitive dovod_N = "довода"
lemmaGenitive dokazatelstvo_N = "доказательства"
lemmaGenitive dolg_N = "долга"
lemmaGenitive dopushchenie_N = "допущения"
lemmaGenitive dostatochnost_N = "достаточности"
lemmaGenitive dostovernost_N = "достоверности"
lemmaGenitive zhizn_N = "жизни"
lemmaGenitive zadacha_N = "задачи"
lemmaGenitive zaklyuchenie_N = "заключения"
lemmaGenitive zapret_N = "запрета"
lemmaGenitive znat_V = "знать"
lemmaGenitive identichnost_N = "идентичности"
lemmaGenitive illyuziya_N = "иллюзии"
lemmaGenitive implikatsiya_N = "импликации"
lemmaGenitive interpretatsiya_N = "интерпретации"
lemmaGenitive inferentsiya_N = "инференции"
lemmaGenitive isklyuchenie_N = "исключения"
lemmaGenitive istina_N = "истины"
lemmaGenitive istinnost_N = "истинности"
lemmaGenitive kvantor_N = "квантора"
lemmaGenitive kontakt_N = "контакта"
lemmaGenitive kontrprimer_N = "контрпримера"
lemmaGenitive konflikt_N = "конфликта"
lemmaGenitive konfrontatsiya_N = "конфронтации"
lemmaGenitive korollarij_N = "короллария"
lemmaGenitive korrektnost_N = "корректности"
lemmaGenitive kriterij_N = "критерия"
lemmaGenitive lemma_N = "леммы"
lemmaGenitive logika_N = "логики"
lemmaGenitive lozh_N = "лжи"
lemmaGenitive lyubov_N = "любви"
lemmaGenitive modalnost_N = "модальности"
lemmaGenitive molchanie_N = "молчания"
lemmaGenitive myslit_V = "мыслить"
lemmaGenitive nadezhda_N = "надежды"
lemmaGenitive nadezhnost_N = "надежности"
lemmaGenitive naznachenie_N = "назначения"
lemmaGenitive neobhodimost_N = "необходимости"
lemmaGenitive neprotivorechivost_N = "непротиворечивости"
lemmaGenitive nesovmestimost_N = "несовместимости"
lemmaGenitive nichto_N = "ничего"
lemmaGenitive obida_N = "обиды"
lemmaGenitive obosnovanie_N = "обоснования"
lemmaGenitive obyasnenie_N = "объяснения"
lemmaGenitive obyazannost_N = "обязанности"
lemmaGenitive obyazatelstvo_N = "обязательства"
lemmaGenitive ogranichenie_N = "ограничения"
lemmaGenitive odinochestvo_N = "одиночества"
lemmaGenitive opisanie_N = "описания"
lemmaGenitive opredelenie_N = "определения"
lemmaGenitive oproverzhenie_N = "опровержения"
lemmaGenitive osnovanie_N = "основания"
lemmaGenitive osnovyvat_V = "основывать"
lemmaGenitive otvet_N = "ответа"
lemmaGenitive otvetstvennost_N = "ответственности"
lemmaGenitive otrazhenie_N = "отражения"
lemmaGenitive oshibka_N = "ошибки"
lemmaGenitive pamyat_N = "памяти"
lemmaGenitive pozitsiya_N = "позиции"
lemmaGenitive ponimanie_N = "понимания"
lemmaGenitive ponimat_V = "понимать"
lemmaGenitive ponyatie_N = "понятия"
lemmaGenitive posylka_N = "посылки"
lemmaGenitive pravda_N = "правды"
lemmaGenitive pravo_N = "права"
lemmaGenitive predpolozhenie_N = "предположения"
lemmaGenitive predposylka_N = "предпосылки"
lemmaGenitive prinuzhdenie_N = "принуждения"
lemmaGenitive prisutstvie_N = "присутствия"
lemmaGenitive prichina_N = "причины"
lemmaGenitive proverka_N = "проверки"
lemmaGenitive proniknut_V = "проникнуть"
lemmaGenitive protivorechie_N = "противоречия"
lemmaGenitive pustota_N = "пустоты"
lemmaGenitive ravnosilnost_N = "равносильности"
lemmaGenitive radost_N = "радости"
lemmaGenitive razgranichenie_N = "разграничения"
lemmaGenitive razlichat_V = "различать"
lemmaGenitive razlichie_N = "различия"
lemmaGenitive raznitsa_N = "разницы"
lemmaGenitive razreshenie_N = "разрешения"
lemmaGenitive razum_N = "разума"
lemmaGenitive rakurs_N = "ракурса"
lemmaGenitive remont_N = "ремонта"
lemmaGenitive reshenie_N = "решения"
lemmaGenitive svidetelstvo_N = "свидетельства"
lemmaGenitive svoboda_N = "свободы"
lemmaGenitive sillogizm_N = "силлогизма"
lemmaGenitive skazat_V = "сказать"
lemmaGenitive sledstvie_N = "следствия"
lemmaGenitive smert_N = "смерти"
lemmaGenitive smirenie_N = "смирения"
lemmaGenitive smysl_N = "смысла"
lemmaGenitive soglasie_N = "согласия"
lemmaGenitive soglasovannost_N = "согласованности"
lemmaGenitive soznanie_N = "сознания"
lemmaGenitive somnenie_N = "сомнения"
lemmaGenitive sposobnost_N = "способности"
lemmaGenitive spravedlivost_N = "справедливости"
lemmaGenitive stradanie_N = "страдания"
lemmaGenitive strah_N = "страха"
lemmaGenitive styd_N = "стыда"
lemmaGenitive sudba_N = "судьбы"
lemmaGenitive suzhdenie_N = "суждения"
lemmaGenitive sushchestvovanie_N = "существования"
lemmaGenitive sushchestvovat_V = "существовать"
lemmaGenitive tezis_N = "тезиса"
lemmaGenitive telo_N = "тела"
lemmaGenitive teorema_N = "теоремы"
lemmaGenitive termin_N = "термина"
lemmaGenitive toska_N = "тоски"
lemmaGenitive trevoga_N = "тревоги"
lemmaGenitive uslovie_N = "условия"
lemmaGenitive utverzhdenie_N = "утверждения"
lemmaGenitive utochnyat_V = "уточнять"
lemmaGenitive utrata_N = "утраты"
lemmaGenitive uhod_N = "ухода"
lemmaGenitive fakt_N = "факта"
lemmaGenitive filosofiya_N = "философии"
lemmaGenitive hrupkost_N = "хрупкости"
lemmaGenitive tsel_N = "цели"
lemmaGenitive tsifra_N = "цифры"
lemmaGenitive chestnost_N = "честности"
lemmaGenitive ekvivalentsiya_N = "эквиваленции"
lemmaGenitive eksplikatsiya_N = "экспликации"
lemmaGenitive entejlment_N = "энтейлмента"
lemmaGenitive yazyk_N = "языка"
lemmaGenitive yakor_N = "якоря"

lemmaPrepositional : Lemma → String
lemmaPrepositional absurd_N = "абсурде"
lemmaPrepositional avtonomiya_N = "автономии"
lemmaPrepositional agentnost_N = "агентности"
lemmaPrepositional aksioma_N = "аксиоме"
lemmaPrepositional antitezis_N = "антитезисе"
lemmaPrepositional argument_N = "аргументе"
lemmaPrepositional bol_N = "боли"
lemmaPrepositional validnost_N = "валидности"
lemmaPrepositional veroyatnost_N = "вероятности"
lemmaPrepositional vechnost_N = "вечности"
lemmaPrepositional vina_N = "вине"
lemmaPrepositional vozmozhnost_N = "возможности"
lemmaPrepositional volya_N = "воле"
lemmaPrepositional vopros_N = "вопросе"
lemmaPrepositional vremya_N = "времени"
lemmaPrepositional vybor_N = "выборе"
lemmaPrepositional vyvod_N = "выводе"
lemmaPrepositional vyvodimost_N = "выводимости"
lemmaPrepositional vyskazyvanie_N = "высказывании"
lemmaPrepositional gipoteza_N = "гипотезе"
lemmaPrepositional gnev_N = "гневе"
lemmaPrepositional gordost_N = "гордости"
lemmaPrepositional granitsa_N = "границе"
lemmaPrepositional delat_V = "делать"
lemmaPrepositional definitsiya_N = "дефиниции"
lemmaPrepositional dialog_N = "диалоге"
lemmaPrepositional distinktsiya_N = "дистинкции"
lemmaPrepositional doverie_N = "доверии"
lemmaPrepositional dovod_N = "доводе"
lemmaPrepositional dokazatelstvo_N = "доказательстве"
lemmaPrepositional dolg_N = "долге"
lemmaPrepositional dopushchenie_N = "допущении"
lemmaPrepositional dostatochnost_N = "достаточности"
lemmaPrepositional dostovernost_N = "достоверности"
lemmaPrepositional zhizn_N = "жизни"
lemmaPrepositional zadacha_N = "задаче"
lemmaPrepositional zaklyuchenie_N = "заключении"
lemmaPrepositional zapret_N = "запрете"
lemmaPrepositional znat_V = "знать"
lemmaPrepositional identichnost_N = "идентичности"
lemmaPrepositional illyuziya_N = "иллюзии"
lemmaPrepositional implikatsiya_N = "импликации"
lemmaPrepositional interpretatsiya_N = "интерпретации"
lemmaPrepositional inferentsiya_N = "инференции"
lemmaPrepositional isklyuchenie_N = "исключении"
lemmaPrepositional istina_N = "истине"
lemmaPrepositional istinnost_N = "истинности"
lemmaPrepositional kvantor_N = "кванторе"
lemmaPrepositional kontakt_N = "контакте"
lemmaPrepositional kontrprimer_N = "контрпримере"
lemmaPrepositional konflikt_N = "конфликте"
lemmaPrepositional konfrontatsiya_N = "конфронтации"
lemmaPrepositional korollarij_N = "королларии"
lemmaPrepositional korrektnost_N = "корректности"
lemmaPrepositional kriterij_N = "критерии"
lemmaPrepositional lemma_N = "лемме"
lemmaPrepositional logika_N = "логике"
lemmaPrepositional lozh_N = "лжи"
lemmaPrepositional lyubov_N = "любви"
lemmaPrepositional modalnost_N = "модальности"
lemmaPrepositional molchanie_N = "молчании"
lemmaPrepositional myslit_V = "мыслить"
lemmaPrepositional nadezhda_N = "надежде"
lemmaPrepositional nadezhnost_N = "надежности"
lemmaPrepositional naznachenie_N = "назначении"
lemmaPrepositional neobhodimost_N = "необходимости"
lemmaPrepositional neprotivorechivost_N = "непротиворечивости"
lemmaPrepositional nesovmestimost_N = "несовместимости"
lemmaPrepositional nichto_N = "ничем"
lemmaPrepositional obida_N = "обиде"
lemmaPrepositional obosnovanie_N = "обосновании"
lemmaPrepositional obyasnenie_N = "объяснении"
lemmaPrepositional obyazannost_N = "обязанности"
lemmaPrepositional obyazatelstvo_N = "обязательстве"
lemmaPrepositional ogranichenie_N = "ограничении"
lemmaPrepositional odinochestvo_N = "одиночестве"
lemmaPrepositional opisanie_N = "описании"
lemmaPrepositional opredelenie_N = "определении"
lemmaPrepositional oproverzhenie_N = "опровержении"
lemmaPrepositional osnovanie_N = "основании"
lemmaPrepositional osnovyvat_V = "основывать"
lemmaPrepositional otvet_N = "ответе"
lemmaPrepositional otvetstvennost_N = "ответственности"
lemmaPrepositional otrazhenie_N = "отражении"
lemmaPrepositional oshibka_N = "ошибке"
lemmaPrepositional pamyat_N = "памяти"
lemmaPrepositional pozitsiya_N = "позиции"
lemmaPrepositional ponimanie_N = "понимании"
lemmaPrepositional ponimat_V = "понимать"
lemmaPrepositional ponyatie_N = "понятии"
lemmaPrepositional posylka_N = "посылке"
lemmaPrepositional pravda_N = "правде"
lemmaPrepositional pravo_N = "праве"
lemmaPrepositional predpolozhenie_N = "предположении"
lemmaPrepositional predposylka_N = "предпосылке"
lemmaPrepositional prinuzhdenie_N = "принуждении"
lemmaPrepositional prisutstvie_N = "присутствии"
lemmaPrepositional prichina_N = "причине"
lemmaPrepositional proverka_N = "проверке"
lemmaPrepositional proniknut_V = "проникнуть"
lemmaPrepositional protivorechie_N = "противоречии"
lemmaPrepositional pustota_N = "пустоте"
lemmaPrepositional ravnosilnost_N = "равносильности"
lemmaPrepositional radost_N = "радости"
lemmaPrepositional razgranichenie_N = "разграничении"
lemmaPrepositional razlichat_V = "различать"
lemmaPrepositional razlichie_N = "различии"
lemmaPrepositional raznitsa_N = "разнице"
lemmaPrepositional razreshenie_N = "разрешении"
lemmaPrepositional razum_N = "разуме"
lemmaPrepositional rakurs_N = "ракурсе"
lemmaPrepositional remont_N = "ремонте"
lemmaPrepositional reshenie_N = "решении"
lemmaPrepositional svidetelstvo_N = "свидетельстве"
lemmaPrepositional svoboda_N = "свободе"
lemmaPrepositional sillogizm_N = "силлогизме"
lemmaPrepositional skazat_V = "сказать"
lemmaPrepositional sledstvie_N = "следствии"
lemmaPrepositional smert_N = "смерти"
lemmaPrepositional smirenie_N = "смирении"
lemmaPrepositional smysl_N = "смысле"
lemmaPrepositional soglasie_N = "согласии"
lemmaPrepositional soglasovannost_N = "согласованности"
lemmaPrepositional soznanie_N = "сознании"
lemmaPrepositional somnenie_N = "сомнении"
lemmaPrepositional sposobnost_N = "способности"
lemmaPrepositional spravedlivost_N = "справедливости"
lemmaPrepositional stradanie_N = "страдании"
lemmaPrepositional strah_N = "страхе"
lemmaPrepositional styd_N = "стыде"
lemmaPrepositional sudba_N = "судьбе"
lemmaPrepositional suzhdenie_N = "суждении"
lemmaPrepositional sushchestvovanie_N = "существовании"
lemmaPrepositional sushchestvovat_V = "существовать"
lemmaPrepositional tezis_N = "тезисе"
lemmaPrepositional telo_N = "теле"
lemmaPrepositional teorema_N = "теореме"
lemmaPrepositional termin_N = "термине"
lemmaPrepositional toska_N = "тоске"
lemmaPrepositional trevoga_N = "тревоге"
lemmaPrepositional uslovie_N = "условии"
lemmaPrepositional utverzhdenie_N = "утверждении"
lemmaPrepositional utochnyat_V = "уточнять"
lemmaPrepositional utrata_N = "утрате"
lemmaPrepositional uhod_N = "уходе"
lemmaPrepositional fakt_N = "факте"
lemmaPrepositional filosofiya_N = "философии"
lemmaPrepositional hrupkost_N = "хрупкости"
lemmaPrepositional tsel_N = "цели"
lemmaPrepositional tsifra_N = "цифре"
lemmaPrepositional chestnost_N = "честности"
lemmaPrepositional ekvivalentsiya_N = "эквиваленции"
lemmaPrepositional eksplikatsiya_N = "экспликации"
lemmaPrepositional entejlment_N = "энтейлменте"
lemmaPrepositional yazyk_N = "языке"
lemmaPrepositional yakor_N = "якоре"

lemmaCount : Nat
lemmaCount = 156

lemmaCountExpected : lemmaCount ≡ 156
lemmaCountExpected = refl

