{-# LANGUAGE OverloadedStrings #-}

{-| Specific proposition detectors extracted from the original Proposition module
(full chain migration completed 2026-06-04).

Contains the ~20 detect*/build*/collect* functions that were pending migration
from Proposition.hs.backup (lines 525-1890).  Generated by extracting and
re-moduling the original detection code.
-}
module QxFx0.Semantic.Proposition.Detectors
  ( -- the detection chain
    detectContactSignal
  , detectOperationalStatus
  , detectOperationalCause
  , detectSystemLogic
  , detectDistinctionQuestion
  , detectConfrontSignal
  , detectNextStepSignal
  , detectAffectiveSupport
  , detectSelfKnowledge
  , detectPurposeFunction
  , detectDialogueInvitation
  , detectConceptKnowledge
  , detectWorldCause
  , detectLocationFormation
  , detectSelfState
  , detectComparisonPlausibility
  , detectMisunderstanding
  , detectRepairDirective
  , detectGenerativePrompt
  , detectContemplativeTopic
  , detectExploratoryPrompt
    -- helper collectors (needed by callers)
  , collectRawContactTriggers
  , collectRawConfrontTriggers
  , collectRawNextStepTriggers
  , collectRawOperationalStatusTriggers
  , collectRawOperationalCauseTriggers
  , collectRawSystemLogicTriggers
  , collectRawDistinctionTriggers
  , collectRawAffectiveSupportProbeTriggers
  , collectRawAffectiveSupportPhraseTriggers
  , collectRawSelfKnowledgeTriggers
  , collectRawPurposeTriggers
  , collectRawDialogueInvitationTriggers
  , collectRawConceptKnowledgeTriggers
  , collectRawWorldCauseTriggers
  , collectRawLocationFormationTriggers
  , collectRawSelfStateTriggers
  , collectRawComparisonPlausibilityTriggers
  , collectRawMisunderstandingTriggers
  , collectRawRepairDirectiveTriggers
  , collectRawGenerativePromptTriggers
  , collectRawContemplativeTopicTriggers
  , collectRawExploratoryPromptTriggers
    -- builders
  , buildContactSignalFromTriggers
  , buildConfrontSignalFromTriggers
  , buildNextStepSignalFromTriggers
  , buildOperationalStatusFromTriggers
  , buildOperationalCauseFromTriggers
  , buildSystemLogicFromTriggers
  , buildDistinctionFromTriggers
  , buildAffectiveSupportFromPhraseTriggers
  , buildAffectiveSupportFromProbeTriggers
  , buildSelfKnowledgeFromTriggers
  , buildPurposeFromTriggers
  , buildDialogueInvitationFromTriggers
  , buildConceptKnowledgeFromTriggers
  , buildWorldCauseFromTriggers
  , buildLocationFormationFromTriggers
  , buildSelfStateFromTriggers
  , buildComparisonPlausibilityFromTriggers
  , buildMisunderstandingFromTriggers
  , buildRepairDirectiveFromTriggers
  , buildGenerativePromptFromTriggers
  , buildContemplativeTopicFromTriggers
  , buildExploratoryPromptFromTriggers
  ) where


import QxFx0.Types
import QxFx0.Semantic.Proposition.Types (PropositionType(..))
import QxFx0.Semantic.Proposition.Focus
import QxFx0.Semantic.Proposition.Semantic
import QxFx0.Types
import Control.Applicative ((<|>))
import QxFx0.Lexicon.Inflection (toNominative)
import QxFx0.Semantic.Morphology (extractContentNouns)
import QxFx0.Policy.ParserKeywords
import QxFx0.Semantic.KeywordMatch
import QxFx0.Types.Admission.PropositionPhraseDecisionAdmission
import QxFx0.Types.Admission.PropositionContactAdmission (admitPropositionContactTriggers)
import QxFx0.Types.Admission.PropositionConfrontAdmission (admitPropositionConfrontTriggers)
import QxFx0.Types.Admission.PropositionNextStepAdmission (admitPropositionNextStepTriggers)
import QxFx0.Types.Admission.PropositionOperationalStatusAdmission (admitPropositionOperationalStatusTriggers)
import QxFx0.Types.Admission.PropositionOperationalCauseAdmission (admitPropositionOperationalCauseTriggers)
import QxFx0.Types.Admission.PropositionSystemLogicAdmission (admitPropositionSystemLogicTriggers)
import QxFx0.Types.Admission.PropositionDistinctionAdmission (admitPropositionDistinctionTriggers)
import QxFx0.Types.Admission.PropositionAffectiveSupportPhraseAdmission (admitPropositionAffectiveSupportPhraseTriggers)
import QxFx0.Types.Admission.PropositionAffectiveSupportProbeAdmission (admitPropositionAffectiveSupportProbeTriggers)
import QxFx0.Types.Admission.PropositionSelfKnowledgeAdmission (admitPropositionSelfKnowledgeTriggers)
import QxFx0.Types.Admission.PropositionPurposeAdmission (admitPropositionPurposeTriggers)
import QxFx0.Types.Admission.PropositionConceptKnowledgeAdmission (admitPropositionConceptKnowledgeTriggers)
import QxFx0.Types.Admission.PropositionMisunderstandingAdmission (admitPropositionMisunderstandingTriggers)
import QxFx0.Types.Admission.PropositionWorldCauseAdmission (admitPropositionWorldCauseTriggers)
import QxFx0.Types.Admission.PropositionLocationFormationAdmission (admitPropositionLocationFormationTriggers)
import QxFx0.Types.Admission.PropositionExploratoryPromptAdmission (admitPropositionExploratoryPromptTriggers)
import QxFx0.Types.Admission.PropositionDialogueInvitationAdmission (admitPropositionDialogueInvitationTriggers)
import QxFx0.Types.Admission.PropositionContemplativeTopicAdmission (admitPropositionContemplativeTopicTriggers)
import QxFx0.Types.Admission.PropositionGenerativePromptAdmission (admitPropositionGenerativePromptTriggers)
import QxFx0.Types.Admission.PropositionComparisonPlausibilityAdmission (admitPropositionComparisonPlausibilityTriggers)
import QxFx0.Types.Admission.PropositionSelfStateAdmission (admitPropositionSelfStateTriggers)
import QxFx0.Types.Admission.PropositionRepairDirectiveAdmission (admitPropositionRepairDirectiveTriggers)
import QxFx0.Types.PropositionAdmissionTypes
import QxFx0.Types.PropositionFallbackAdmission
import QxFx0.Semantic.Input.Assemble (buildUtteranceSemanticFrame, buildUtteranceSemanticFrameMorph)
import QxFx0.Semantic.Input.Model
import QxFx0.Policy.SemanticScoring
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.List as L
import qualified Data.Char as Char
import QxFx0.Types.Text (textShow)
import qualified Data.Map.Strict as M
import Data.Maybe (fromMaybe, listToMaybe, catMaybes, mapMaybe)
import Text.Read (readMaybe)

detectContactSignal :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectContactSignal truthContractStatus rawText tokens =
  buildContactSignalFromTriggers rawText tokens admittedTriggerList
  where
    rawTriggers = collectRawContactTriggers rawText tokens
    admittedTriggers =
      admitPropositionContactTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers
    AdmittedPropositionTriggers _ admittedTriggerList _ = admittedTriggers

collectRawContactTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawContactTriggers rawText tokens =
  [ RawPropositionTrigger "exclude_how_you_work" (containsKeywordPhrase tokens "как ты работаешь")
  , RawPropositionTrigger "exclude_how_you_work_plural" (containsKeywordPhrase tokens "как вы работаете")
  , RawPropositionTrigger "exclude_how_you_built" (containsKeywordPhrase tokens "как ты устроен")
  , RawPropositionTrigger "how_are_you" (containsKeywordPhrase tokens "как дела")
  , RawPropositionTrigger "how_is_life" (containsKeywordPhrase tokens "как жизнь")
  , RawPropositionTrigger "short_how_you"
      (containsKeywordPhrase tokens "как ты" && isShortHowYouContact tokens)
  , RawPropositionTrigger "greeting"
      (T.toLower (T.strip rawText) `elem` ["привет", "здравствуй", "здравствуйте", "салют", "хай", "hello", "hi"])
  , RawPropositionTrigger "courtesy_infix"
      (any (`T.isInfixOf` T.toLower rawText) ["добрый день", "доброе утро", "добрый вечер", "рад видеть"])
  , RawPropositionTrigger "farewell" (containsKeywordPhrase tokens "до свидания")
  , RawPropositionTrigger "parting_meeting" (containsKeywordPhrase tokens "до встречи")
  , RawPropositionTrigger "good_wishes" (containsKeywordPhrase tokens "всего доброго")
  , RawPropositionTrigger "good_wishes_alt" (containsKeywordPhrase tokens "всего хорошего")
  , RawPropositionTrigger "brief_contact_probe"
      (any (`elem` tokens) ["пока", "прощай", "бывай", "увидимся", "спасибо", "благодарю", "thanks"])
  , RawPropositionTrigger "how_self" (containsKeywordPhrase tokens "как сам")
  , RawPropositionTrigger "how_mood" (containsKeywordPhrase tokens "как настроение")
  , RawPropositionTrigger "glad_to_see_you" (containsKeywordPhrase tokens "рад тебя видеть")
  , RawPropositionTrigger "glad_to_see_you_plural" (containsKeywordPhrase tokens "рад вас видеть")
  , RawPropositionTrigger "start_conversation" (containsKeywordPhrase tokens "начнем разговор")
  , RawPropositionTrigger "start_conversation_alt" (containsKeywordPhrase tokens "начнём разговор")
  , RawPropositionTrigger "can_chat" (containsKeywordPhrase tokens "можем пообщаться")
  , RawPropositionTrigger "returned" (containsKeywordPhrase tokens "я вернулся")
  , RawPropositionTrigger "greeting_again" (containsKeywordPhrase tokens "снова привет")
  , RawPropositionTrigger "ready_to_talk" (containsKeywordPhrase tokens "готов к разговору")
  , RawPropositionTrigger "contact_present" (containsKeywordPhrase tokens "контакт есть")
  , RawPropositionTrigger "contact_present_alt" (containsKeywordPhrase tokens "есть контакт")
  , RawPropositionTrigger "connected" (containsKeywordPhrase tokens "мы на связи")
  , RawPropositionTrigger "can_you_hear_me" (containsKeywordPhrase tokens "слышишь меня")
  , RawPropositionTrigger "online" (containsKeywordPhrase tokens "ты онлайн")
  , RawPropositionTrigger "short_dialogue_probe"
      (shortDialogueProbe tokens && any (`elem` tokens) ["поговорим", "обсудим"])
  , RawPropositionTrigger "can_we_talk_about" (T.isInfixOf "can we talk about" (T.toLower rawText))
  , RawPropositionTrigger "lets_discuss" (T.isInfixOf "let's discuss" (T.toLower rawText))
  , RawPropositionTrigger "question_about" (T.isInfixOf "i have a question about" (T.toLower rawText))
  , RawPropositionTrigger "want_to_understand" (T.isInfixOf "i want to understand" (T.toLower rawText))
  , RawPropositionTrigger "who_determines" (T.isInfixOf "who determines" (T.toLower rawText))
  , RawPropositionTrigger "who_is_responsible" (T.isInfixOf "who is responsible" (T.toLower rawText))
  , RawPropositionTrigger "what_agency" (T.isInfixOf "what agency" (T.toLower rawText))
  , RawPropositionTrigger "what_role_does" (T.isInfixOf "what role does" (T.toLower rawText))
  , RawPropositionTrigger "how_does_agency" (T.isInfixOf "how does agency" (T.toLower rawText))
  ]
  where
    shortDialogueProbe ts = length ts <= 2

buildContactSignalFromTriggers :: Text -> [Text] -> [RawPropositionTrigger] -> Maybe PropositionType
buildContactSignalFromTriggers rawText tokens admittedTriggers
  | matched "exclude_how_you_work" = Nothing
  | matched "exclude_how_you_work_plural" = Nothing
  | matched "exclude_how_you_built" = Nothing
  | matched "how_are_you" = Just ContactSignal
  | matched "how_is_life" = Just ContactSignal
  | matched "short_how_you"
      && not (matched "exclude_how_you_built")
      && not (matched "exclude_how_you_work") = Just ContactSignal
  | matched "greeting" = Just ContactSignal
  | matched "courtesy_infix" = Just ContactSignal
  | matched "farewell" = Just ContactSignal
  | matched "parting_meeting" = Just ContactSignal
  | matched "good_wishes" = Just ContactSignal
  | matched "good_wishes_alt" = Just ContactSignal
  | matched "brief_contact_probe" = Just ContactSignal
  | matched "how_self" = Just ContactSignal
  | matched "how_mood" = Just ContactSignal
  | matched "glad_to_see_you" = Just ContactSignal
  | matched "glad_to_see_you_plural" = Just ContactSignal
  | matched "start_conversation" = Just ContactSignal
  | matched "start_conversation_alt" = Just ContactSignal
  | matched "can_chat" = Just ContactSignal
  | matched "returned" = Just ContactSignal
  | matched "greeting_again" = Just ContactSignal
  | matched "ready_to_talk" = Just ContactSignal
  | matched "contact_present" = Just ContactSignal
  | matched "contact_present_alt" = Just ContactSignal
  | matched "connected" = Just ContactSignal
  | matched "can_you_hear_me" = Just ContactSignal
  | matched "online" = Just ContactSignal
  | matched "short_dialogue_probe" = Just ContactSignal
  | matched "can_we_talk_about" = Just ContactSignal
  | matched "lets_discuss" = Just ContactSignal
  | matched "question_about" = Just ContactSignal
  | matched "want_to_understand" = Just ContactSignal
  | matched "who_determines" = Just ContactSignal
  | matched "who_is_responsible" = Just ContactSignal
  | matched "what_agency" = Just ContactSignal
  | matched "what_role_does" = Just ContactSignal
  | matched "how_does_agency" = Just ContactSignal
  | otherwise = Nothing
  where
    _unused = rawText
    _unusedTokens = tokens
    matched label = any hasMatchingLabel admittedTriggers
      where
        hasMatchingLabel (RawPropositionTrigger triggerLabel triggerMatched) =
          triggerLabel == label && triggerMatched

isShortHowYouContact :: [Text] -> Bool
isShortHowYouContact tokens =
  length tokens <= 4
    && not (any (`elem` tokens) ["будешь", "будете", "можешь", "можете", "умеешь", "умеете", "определять", "сделать", "делать", "объяснить"])

detectOperationalStatus :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectOperationalStatus truthContractStatus rawText tokens =
  buildOperationalStatusFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawOperationalStatusTriggers rawText tokens
    admittedTriggers =
      admitPropositionOperationalStatusTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawOperationalStatusTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawOperationalStatusTriggers rawText tokens =
  [ RawPropositionTrigger "work_text_cue" (T.isInfixOf "работа" (T.toLower rawText))
  , RawPropositionTrigger "subject_present" (any (`elem` tokens) ["ты", "система"])
  , RawPropositionTrigger "why_guard_clear" (not (containsKeywordPhrase tokens "почему"))
  ]

buildOperationalStatusFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildOperationalStatusFromTriggers admittedTriggers
  | matched "work_text_cue"
      && matched "subject_present"
      && matched "why_guard_clear" = Just OperationalStatusQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectOperationalCause :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectOperationalCause truthContractStatus rawText tokens =
  buildOperationalCauseFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawOperationalCauseTriggers rawText tokens
    admittedTriggers =
      admitPropositionOperationalCauseTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawOperationalCauseTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawOperationalCauseTriggers rawText tokens =
  [ RawPropositionTrigger "why_phrase" (containsKeywordPhrase tokens "почему")
  , RawPropositionTrigger "work_text_cue" (T.isInfixOf "работа" (T.toLower rawText))
  , RawPropositionTrigger "subject_present" (any (`elem` tokens) ["ты", "система"])
  ]

buildOperationalCauseFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildOperationalCauseFromTriggers admittedTriggers
  | matched "why_phrase"
      && matched "work_text_cue"
      && matched "subject_present" = Just OperationalCauseQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectSystemLogic :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectSystemLogic truthContractStatus rawText tokens =
  buildSystemLogicFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawSystemLogicTriggers rawText tokens
    admittedTriggers =
      admitPropositionSystemLogicTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawSystemLogicTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawSystemLogicTriggers rawText tokens =
  [ RawPropositionTrigger "how_you_will" (containsKeywordPhrase tokens "как ты будешь")
  , RawPropositionTrigger "how_you_will_plural" (containsKeywordPhrase tokens "как вы будете")
  , RawPropositionTrigger "logic_tokens_present" (any (`elem` tokens) ["логика", "устроен", "работаешь"])
  , RawPropositionTrigger "subject_present" (any (`elem` tokens) ["твоя", "ты"])
  , RawPropositionTrigger "your_logic_text" (T.isInfixOf "твоя логика" (T.toLower rawText))
  ]

buildSystemLogicFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildSystemLogicFromTriggers admittedTriggers
  | matched "how_you_will" = Just SystemLogicQ
  | matched "how_you_will_plural" = Just SystemLogicQ
  | matched "logic_tokens_present"
      && matched "subject_present" = Just SystemLogicQ
  | matched "your_logic_text" = Just SystemLogicQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectDistinctionQuestion :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectDistinctionQuestion truthContractStatus rawText tokens =
  let lowered = T.toLower rawText
      rawTriggers = collectRawDistinctionTriggers lowered tokens
      admittedTriggers =
        admitPropositionDistinctionTriggers
          (PropositionAdmissionInput truthContractStatus)
          rawTriggers
  in buildDistinctionFromTriggers (aptTriggers admittedTriggers)

collectRawDistinctionTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawDistinctionTriggers lowered tokens =
  [ RawPropositionTrigger "complex_relationship_between_how_differ"
      (T.isInfixOf "relationship between" lowered && T.isInfixOf "how do they differ" lowered)
  , RawPropositionTrigger "complex_distinguish_then_ground"
      (T.isInfixOf "distinguish" lowered && T.isInfixOf "then ground" lowered)
  , RawPropositionTrigger "complex_how_differ_practical_reasoning"
      (T.isInfixOf "how does it differ" lowered && T.isInfixOf "in practical reasoning" lowered)
  , RawPropositionTrigger "complex_why_differ"
      (T.isInfixOf "why" lowered && T.isInfixOf "differ" lowered)
  , RawPropositionTrigger "complex_for_what_purpose_distinguish"
      (T.isInfixOf "for what purpose" lowered && T.isInfixOf "distinguish" lowered)
  , RawPropositionTrigger "complex_why_distinguish"
      (T.isInfixOf "why" lowered && T.isInfixOf "distinguish" lowered)
  , RawPropositionTrigger "how_distinguish_phrase"
      (containsKeywordPhrase tokens "как отличить")
  , RawPropositionTrigger "from_token_present"
      (any (`elem` tokens) ["от"])
  , RawPropositionTrigger "what_differs_phrase"
      (containsKeywordPhrase tokens "чем отличается")
  , RawPropositionTrigger "how_distinguish_text"
      (T.isInfixOf "как отличить" lowered && T.isInfixOf " от " lowered)
  , RawPropositionTrigger "differentiate_between_text"
      (T.isInfixOf "differentiate between" lowered)
  , RawPropositionTrigger "differentiate_text"
      (T.isInfixOf "differentiate" lowered)
  , RawPropositionTrigger "distinguish_between_text"
      (T.isInfixOf "distinguish between" lowered)
  , RawPropositionTrigger "difference_between_text"
      (T.isInfixOf "difference between" lowered)
  , RawPropositionTrigger "distinction_between_text"
      (T.isInfixOf "distinction between" lowered)
  , RawPropositionTrigger "differ_from_text"
      (T.isInfixOf "differ from" lowered)
  , RawPropositionTrigger "differ_question_text"
      (T.isInfixOf "differ?" lowered)
  , RawPropositionTrigger "differ_comma_text"
      (T.isInfixOf "differ," lowered)
  , RawPropositionTrigger "differ_period_text"
      (T.isInfixOf "differ." lowered)
  , RawPropositionTrigger "differ_spaced_text"
      (T.isInfixOf " differ " lowered)
  , RawPropositionTrigger "contrast_text"
      (T.isInfixOf "contrast" lowered)
  , RawPropositionTrigger "ru_raznitsa_mezhdu"
      (T.isInfixOf "разница между" lowered)
  , RawPropositionTrigger "ru_raznitsa_i"
      (T.isInfixOf "разница" lowered && T.isInfixOf " и " lowered)
  , RawPropositionTrigger "ru_chem_raznitsa"
      (containsKeywordPhrase tokens "в чём разница" || containsKeywordPhrase tokens "в чем разница")
  , RawPropositionTrigger "ru_otlichie"
      (T.isInfixOf "отличие" lowered && T.isInfixOf " между " lowered)
  ]

buildDistinctionFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildDistinctionFromTriggers admittedTriggers
  | matched "complex_relationship_between_how_differ" = Nothing
  | matched "complex_distinguish_then_ground" = Nothing
  | matched "complex_how_differ_practical_reasoning" = Nothing
  | matched "complex_why_differ" = Nothing
  | matched "complex_for_what_purpose_distinguish" = Nothing
  | matched "complex_why_distinguish" = Nothing
  | matched "how_distinguish_phrase"
      && matched "from_token_present" = Just DistinctionQ
  | matched "what_differs_phrase" = Just DistinctionQ
  | matched "how_distinguish_text" = Just DistinctionQ
  | matched "differentiate_between_text" = Just DistinctionQ
  | matched "differentiate_text" = Just DistinctionQ
  | matched "distinguish_between_text" = Just DistinctionQ
  | matched "difference_between_text" = Just DistinctionQ
  | matched "distinction_between_text" = Just DistinctionQ
  | matched "differ_from_text" = Just DistinctionQ
  | matched "differ_question_text" = Just DistinctionQ
  | matched "differ_comma_text" = Just DistinctionQ
  | matched "differ_period_text" = Just DistinctionQ
  | matched "differ_spaced_text" = Just DistinctionQ
  | matched "contrast_text" = Just DistinctionQ
  | matched "ru_raznitsa_mezhdu" = Just DistinctionQ
  | matched "ru_raznitsa_i" = Just DistinctionQ
  | matched "ru_chem_raznitsa" = Just DistinctionQ
  | matched "ru_otlichie" = Just DistinctionQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectConfrontSignal :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectConfrontSignal truthContractStatus rawText tokens =
  buildConfrontSignalFromTriggers rawText (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawConfrontTriggers rawText tokens
    admittedTriggers =
      admitPropositionConfrontTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawConfrontTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawConfrontTriggers rawText tokens =
  [ RawPropositionTrigger "contradiction_phrase" (containsKeywordPhrase tokens "это противоречие")
  , RawPropositionTrigger "disagree_masc" (containsKeywordPhrase tokens "я не согласен")
  , RawPropositionTrigger "disagree_fem" (containsKeywordPhrase tokens "я не согласна")
  , RawPropositionTrigger "contradiction_noun" ("противоречие" `elem` tokens)
  , RawPropositionTrigger "contradicts_verb" ("противоречит" `elem` tokens)
  , RawPropositionTrigger "contradicts_verb_2sg" ("противоречишь" `elem` tokens)
  , RawPropositionTrigger "doubt_marker" ("сомневаюсь" `elem` tokens)
  , RawPropositionTrigger "disputable_marker" ("спорно" `elem` tokens)
  , RawPropositionTrigger "does_not_follow" (T.isInfixOf "does not follow" (T.toLower rawText))
  , RawPropositionTrigger "ru_razve" ("разве" `elem` tokens)
  , RawPropositionTrigger "ru_neverno" (T.isInfixOf "это неверно" (T.toLower rawText) || T.isInfixOf "ты ошибаешься" (T.toLower rawText))
  , RawPropositionTrigger "ru_ne_prav" (T.isInfixOf "не прав" (T.toLower rawText) || T.isInfixOf "неправ" (T.toLower rawText))
  ]

buildConfrontSignalFromTriggers :: Text -> [RawPropositionTrigger] -> Maybe PropositionType
buildConfrontSignalFromTriggers rawText admittedTriggers
  | matched "contradiction_phrase" = Just ConfrontQ
  | matched "disagree_masc" = Just ConfrontQ
  | matched "disagree_fem" = Just ConfrontQ
  | matched "contradiction_noun" = Just ConfrontQ
  | matched "contradicts_verb" = Just ConfrontQ
  | matched "doubt_marker" = Just ConfrontQ
  | matched "disputable_marker" = Just ConfrontQ
  | matched "does_not_follow" = Just ConfrontQ
  | matched "contradicts_verb_2sg" = Just ConfrontQ
  | matched "ru_razve" = Just ConfrontQ
  | matched "ru_neverno" = Just ConfrontQ
  | matched "ru_ne_prav" = Just ConfrontQ
  | otherwise = Nothing
  where
    _unused = rawText
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectNextStepSignal :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectNextStepSignal truthContractStatus rawText tokens =
  buildNextStepSignalFromTriggers rawText (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawNextStepTriggers rawText tokens
    admittedTriggers =
      admitPropositionNextStepTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawNextStepTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawNextStepTriggers rawText tokens =
  [ RawPropositionTrigger "what_next" (containsKeywordPhrase tokens "что дальше")
  , RawPropositionTrigger "next_what" (containsKeywordPhrase tokens "дальше что")
  , RawPropositionTrigger "what_now" (containsKeywordPhrase tokens "что теперь")
  , RawPropositionTrigger "what_after" (containsKeywordPhrase tokens "что потом")
  , RawPropositionTrigger "where_to_start" (containsKeywordPhrase tokens "с чего начать")
  , RawPropositionTrigger "first_step" (containsKeywordPhrase tokens "какой первый шаг")
  , RawPropositionTrigger "what_should_i_do_next" (containsKeywordPhrase tokens "что мне делать дальше")
  , RawPropositionTrigger "how_to_act_next" (containsKeywordPhrase tokens "как действовать дальше")
  , RawPropositionTrigger "no_understanding_what_next" (containsKeywordPhrase tokens "нет понимания что дальше")
  , RawPropositionTrigger "direct_text_short" (T.toLower (T.strip rawText) `elem` ["дальше", "что дальше?"])
  ]

buildNextStepSignalFromTriggers :: Text -> [RawPropositionTrigger] -> Maybe PropositionType
buildNextStepSignalFromTriggers rawText admittedTriggers
  | matched "what_next" = Just NextStepQ
  | matched "next_what" = Just NextStepQ
  | matched "what_now" = Just NextStepQ
  | matched "what_after" = Just NextStepQ
  | matched "where_to_start" = Just NextStepQ
  | matched "first_step" = Just NextStepQ
  | matched "what_should_i_do_next" = Just NextStepQ
  | matched "how_to_act_next" = Just NextStepQ
  | matched "no_understanding_what_next" = Just NextStepQ
  | matched "direct_text_short" = Just NextStepQ
  | otherwise = Nothing
  where
    _unused = rawText
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectAffectiveSupport :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectAffectiveSupport truthContractStatus rawText tokens
  | phraseResult == Just ContactSignal = phraseResult
  | probeResult == Just ContactSignal = probeResult
  | otherwise = Nothing
  where
    rawPhraseTriggers = collectRawAffectiveSupportPhraseTriggers tokens
    admittedPhraseTriggers =
      admitPropositionAffectiveSupportPhraseTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawPhraseTriggers
    phraseResult = buildAffectiveSupportFromPhraseTriggers (aptTriggers admittedPhraseTriggers)
    rawProbeTriggers = collectRawAffectiveSupportProbeTriggers rawText tokens
    admittedProbeTriggers =
      admitPropositionAffectiveSupportProbeTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawProbeTriggers
    probeResult = buildAffectiveSupportFromProbeTriggers (aptTriggers admittedProbeTriggers)

collectRawAffectiveSupportProbeTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawAffectiveSupportProbeTriggers rawText tokens =
  [ RawPropositionTrigger "question_gate" (T.isSuffixOf "?" (T.strip rawText))
  , RawPropositionTrigger "affective_lexeme_probe" hasAffectiveLexeme
  , RawPropositionTrigger "relaxed_regulation_probe" hasRelaxedRegulationProbe
  ]
  where
    hasAffectiveLexeme =
      any (`elem` tokens)
        [ "тревожно", "тревога", "грустно", "тоскливо", "плохо", "одиноко", "страшно"
        , "паника", "апатия", "выгорел", "выгорела", "переживать", "переживаю"
        , "волноваться", "волнуюсь", "устал", "устала", "сил", "тяжело"
        ]
    hasRelaxedRegulationProbe =
      any (`elem` tokens) ["как"]
        && any (\tok -> any (`T.isPrefixOf` tok) ["пережив", "волнов", "тревож", "паник", "успок", "апат"]) tokens

collectRawAffectiveSupportPhraseTriggers :: [Text] -> [RawPropositionTrigger]
collectRawAffectiveSupportPhraseTriggers tokens =
  [ RawPropositionTrigger "how_not_to_worry" (containsKeywordPhrase tokens "как не переживать")
  , RawPropositionTrigger "how_not_to_fret" (containsKeywordPhrase tokens "как не волноваться")
  , RawPropositionTrigger "how_to_calm_down" (containsKeywordPhrase tokens "как успокоиться")
  , RawPropositionTrigger "how_keep_calm" (containsKeywordPhrase tokens "как сохранить спокойствие")
  , RawPropositionTrigger "how_hold_calm" (containsKeywordPhrase tokens "как держать спокойствие")
  , RawPropositionTrigger "how_not_to_panic" (containsKeywordPhrase tokens "как не паниковать")
  , RawPropositionTrigger "how_stop_worrying" (containsKeywordPhrase tokens "как перестать тревожиться")
  , RawPropositionTrigger "how_not_to_feel_anxious" (containsKeywordPhrase tokens "как не тревожиться")
  , RawPropositionTrigger "how_exit_apathy" (containsKeywordPhrase tokens "как выйти из апатии")
  , RawPropositionTrigger "how_restore_motivation" (containsKeywordPhrase tokens "как вернуть мотивацию")
  , RawPropositionTrigger "how_restore_strength" (containsKeywordPhrase tokens "как вернуть силы")
  , RawPropositionTrigger "how_find_strength" (containsKeywordPhrase tokens "как найти силы")
  , RawPropositionTrigger "how_stop_being_upset" (containsKeywordPhrase tokens "как перестать переживать")
  , RawPropositionTrigger "how_stop_fretting" (containsKeywordPhrase tokens "как перестать волноваться")
  , RawPropositionTrigger "how_cope_anxiety" (containsKeywordPhrase tokens "как справиться с тревогой")
  , RawPropositionTrigger "how_cope_fear" (containsKeywordPhrase tokens "как справиться со страхом")
  , RawPropositionTrigger "how_cope_apathy" (containsKeywordPhrase tokens "как справиться с апатией")
  , RawPropositionTrigger "what_to_do_if_anxious" (containsKeywordPhrase tokens "что делать если тревожно")
  , RawPropositionTrigger "what_to_do_if_scared" (containsKeywordPhrase tokens "что делать если страшно")
  , RawPropositionTrigger "what_to_do_when_anxious" (containsKeywordPhrase tokens "что делать когда тревожно")
  , RawPropositionTrigger "what_to_do_when_bad" (containsKeywordPhrase tokens "что делать когда плохо")
  , RawPropositionTrigger "what_to_do_when_sad" (containsKeywordPhrase tokens "что делать когда грустно")
  , RawPropositionTrigger "dont_want_to_do_anything" (containsKeywordPhrase tokens "не хочется ничего делать")
  , RawPropositionTrigger "nothing_wanted_to_do" (containsKeywordPhrase tokens "ничего не хочется делать")
  , RawPropositionTrigger "no_strength" (containsKeywordPhrase tokens "нет сил")
  , RawPropositionTrigger "no_energy" (containsKeywordPhrase tokens "нет энергии")
  , RawPropositionTrigger "hands_drop" (containsKeywordPhrase tokens "руки опускаются")
  , RawPropositionTrigger "nothing_pleases" (containsKeywordPhrase tokens "ничего не радует")
  , RawPropositionTrigger "nothing_wanted" (containsKeywordPhrase tokens "ничего не хочу")
  , RawPropositionTrigger "cant_pull_together" (containsKeywordPhrase tokens "не могу собраться")
  , RawPropositionTrigger "everything_annoys" (containsKeywordPhrase tokens "все бесит")
  , RawPropositionTrigger "everything_annoys_alt" (containsKeywordPhrase tokens "всё бесит")
  , RawPropositionTrigger "tired_and_nothing_wanted" (containsKeywordPhrase tokens "устал и ничего не хочется")
  , RawPropositionTrigger "tired_fem_and_nothing_wanted" (containsKeywordPhrase tokens "устала и ничего не хочется")
  ]

buildAffectiveSupportFromPhraseTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildAffectiveSupportFromPhraseTriggers admittedTriggers
  | any rptMatched admittedTriggers = Just ContactSignal
  | otherwise = Nothing

buildAffectiveSupportFromProbeTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildAffectiveSupportFromProbeTriggers admittedTriggers
  | matched "question_gate" && matched "affective_lexeme_probe" = Just ContactSignal
  | matched "question_gate" && matched "relaxed_regulation_probe" = Just ContactSignal
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

specialFocusEntity :: PropositionType -> Maybe Text
specialFocusEntity OperationalStatusQ = Just "работа"
specialFocusEntity OperationalCauseQ = Just "работа"
specialFocusEntity SystemLogicQ = Just "логика"
specialFocusEntity SelfKnowledgeQ = Just "себя"
specialFocusEntity DialogueInvitationQ = Nothing
specialFocusEntity ConceptKnowledgeQ = Nothing
specialFocusEntity WorldCauseQ = Just "причина"
specialFocusEntity LocationFormationQ = Just "мысль"
specialFocusEntity SelfStateQ = Just "состояние"
specialFocusEntity ComparisonPlausibilityQ = Just "сравнение"
specialFocusEntity MisunderstandingReport = Just "понимание"
specialFocusEntity GenerativePrompt = Just "мысль"
specialFocusEntity ContemplativeTopic = Nothing
specialFocusEntity ExploratoryPrompt = Just "исследование"
specialFocusEntity _ = Nothing

inferSemanticSlots :: Text -> [Text] -> PropositionType -> (Text, Text, [Text], [Text])
inferSemanticSlots rawText tokens propType =
  case propType of
    OperationalStatusQ ->
      ("система", "работа", [], semanticEvidenceFor rawText tokens propType)
    OperationalCauseQ ->
      ("система", "работа", [], semanticEvidenceFor rawText tokens propType)
    SystemLogicQ ->
      ("система", "логика", [], semanticEvidenceFor rawText tokens propType)
    SelfKnowledgeQ ->
      let lowered = T.toLower rawText
          target
            | asksAboutUser rawText = "user"
            | T.isInfixOf "помоч" lowered = "user_help"
            | any (`T.isInfixOf` lowered) ["намерени"] = "self_intentions"
            | any (`T.isInfixOf` lowered) ["важно", "ценност", "послание миру"] = "self_values"
            | any (`T.isInfixOf` lowered) ["будущ"] = "self_future"
            | any (`T.isInfixOf` lowered) ["свобод"] = "self_freedom"
            | any (`T.isInfixOf` lowered) ["промт", "prompt", "субъект", "субьект", "умный", "сложная система"] = "self_reflection"
            | any (`T.isInfixOf` lowered) ["свой же вопрос", "свой вопрос"] = "self_reflection"
            | any (`T.isInfixOf` lowered) ["умеешь", "можешь"] = "self_capability"
            | otherwise = "self"
          subject =
            case target of
              "user" -> "пользователь"
              "user_help" -> fromMaybe "помощь" (capabilitySubject tokens)
              "self_capability" -> fromMaybe "способность" (capabilitySubject tokens)
              "self_intentions" -> "намерения"
              "self_values" -> "принципы"
              "self_future" -> "будущее"
              "self_freedom" -> "свобода"
              "self_reflection" -> "саморефлексия"
              _ -> "система"
      in (subject, target, [], semanticEvidenceFor rawText tokens propType)
    DialogueInvitationQ ->
      (invitationTopic rawText, "dialogue", [], semanticEvidenceFor rawText tokens propType)
    ConceptKnowledgeQ ->
      (conceptSubject rawText tokens, "concept", [], semanticEvidenceFor rawText tokens propType)
    WorldCauseQ ->
      (fromMaybe "мир" (firstConcreteWorldNoun tokens), "причина", [], semanticEvidenceFor rawText tokens propType)
    LocationFormationQ ->
      (fromMaybe "мысль" (firstMentalNoun tokens), "источник", [], semanticEvidenceFor rawText tokens propType)
    SelfStateQ ->
      ("система", "внутренний_фокус", [], semanticEvidenceFor rawText tokens propType)
    PurposeQ ->
      let subject
            | any (`elem` tokens) ["ты", "вы", "система"] = "система"
            | any (`elem` tokens) ["тут", "здесь", "там"] = "объект"
            | otherwise = fromMaybe "объект" (extractTopicAfterMarkers rawText ["для", "у", "в", "о", "об", "про"])
      in (subject, "назначение", [], semanticEvidenceFor rawText tokens propType)
    ComparisonPlausibilityQ ->
      let candidates = comparisonCandidates rawText
      in ("сравнение", "логичность", candidates, semanticEvidenceFor rawText tokens propType)
    DistinctionQ ->
      let candidates = comparisonCandidates rawText
      in ("сравнение", "различение", candidates, semanticEvidenceFor rawText tokens propType)
    MisunderstandingReport ->
      ("диалог", "взаимопонимание", [], semanticEvidenceFor rawText tokens propType)
    GenerativePrompt ->
      ("", "порождение", [], semanticEvidenceFor rawText tokens propType)
    ContemplativeTopic ->
      (contemplativeTopic rawText, "созерцание", [], semanticEvidenceFor rawText tokens propType)
    _ ->
      ("", "", [], semanticEvidenceFor rawText tokens propType)

detectSelfKnowledge :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectSelfKnowledge truthContractStatus rawText tokens =
  buildSelfKnowledgeFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawSelfKnowledgeTriggers rawText tokens
    admittedTriggers =
      admitPropositionSelfKnowledgeTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawSelfKnowledgeTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawSelfKnowledgeTriggers rawText tokens =
  let lowered = T.toLower rawText
  in [ RawPropositionTrigger "who_are_you_ru" (T.isInfixOf "кто ты" lowered)
     , RawPropositionTrigger "who_am_i_ru" (T.isInfixOf "кто я" lowered)
     , RawPropositionTrigger "what_is_your_name_sg" (T.isInfixOf "как тебя зовут" lowered)
     , RawPropositionTrigger "what_is_your_name_pl" (T.isInfixOf "как вас зовут" lowered)
     , RawPropositionTrigger "what_are_you_being" (T.isInfixOf "что ты есть" lowered)
     , RawPropositionTrigger "what_am_i" (T.isInfixOf "что я такое" lowered)
     , RawPropositionTrigger "what_are_you" (T.isInfixOf "что ты такое" lowered)
     , RawPropositionTrigger "what_kind_of_being_are_you" (T.isInfixOf "чем ты являешься" lowered)
     , RawPropositionTrigger "who_kind_of_being_are_you" (T.isInfixOf "кем ты являешься" lowered)
     , RawPropositionTrigger "what_can_you_do_phrase" (T.isInfixOf "что ты умеешь" lowered)
     , RawPropositionTrigger "you_can_do" (T.isInfixOf "ты умеешь" lowered)
     , RawPropositionTrigger "you_can_help" (T.isInfixOf "ты можешь" lowered && T.isInfixOf "помоч" lowered)
     , RawPropositionTrigger "what_can_you_do" (T.isInfixOf "что ты можешь" lowered)
     , RawPropositionTrigger "what_limits_you" (T.isInfixOf "чем ты ограничен" lowered)
     , RawPropositionTrigger "what_do_you_do_now" (T.isInfixOf "что ты делаешь сейчас" lowered)
     , RawPropositionTrigger "how_is_your_answer_built" (T.isInfixOf "как устроен твой ответ" lowered)
     , RawPropositionTrigger "what_is_inside_you" (T.isInfixOf "что у тебя внутри" lowered)
     , RawPropositionTrigger "how_do_you_decide" (T.isInfixOf "как ты принимаешь решение" lowered)
     , RawPropositionTrigger "how_do_you_choose_words" (T.isInfixOf "как ты выбираешь слова" lowered)
     , RawPropositionTrigger "what_do_you_consider_important" (T.isInfixOf "что ты считаешь важным" lowered)
     , RawPropositionTrigger "do_you_understand_context" (T.isInfixOf "ты понимаешь контекст" lowered)
     , RawPropositionTrigger "do_you_remember_dialogue" (T.isInfixOf "ты запоминаешь диалог" lowered)
     , RawPropositionTrigger "how_do_you_hold_frame" (T.isInfixOf "как ты держишь рамку" lowered)
     , RawPropositionTrigger "what_is_in_your_focus" (T.isInfixOf "что у тебя в фокусе" lowered)
     , RawPropositionTrigger "do_you_distinguish_topics" (T.isInfixOf "ты различаешь темы" lowered)
     , RawPropositionTrigger "are_you_smart" (T.isInfixOf "ты умный" lowered)
     , RawPropositionTrigger "are_you_free" (T.isInfixOf "ты свободен" lowered)
     , RawPropositionTrigger "are_you_complex_system" (T.isInfixOf "ты сложная система" lowered)
     , RawPropositionTrigger "are_you_subjective" (T.isInfixOf "ты субъектен" lowered)
     , RawPropositionTrigger "are_you_subjective_typo" (T.isInfixOf "ты субьектен" lowered)
     , RawPropositionTrigger "prompts_act_on_you_ru" (T.isInfixOf "на тебя действуют промты" lowered)
     , RawPropositionTrigger "prompts_act_on_you_en" (T.isInfixOf "на тебя действуют prompt" lowered)
     , RawPropositionTrigger "do_you_have_intentions" (T.isInfixOf "у тебя есть намерения" lowered)
     , RawPropositionTrigger "do_you_have_any_intentions" (T.isInfixOf "есть ли у тебя намерения" lowered)
     , RawPropositionTrigger "do_you_have_message" (T.isInfixOf "у тебя есть послание миру" lowered)
     , RawPropositionTrigger "what_matters_to_you" (T.isInfixOf "что для тебя важно" lowered)
     , RawPropositionTrigger "what_is_your_future" (T.isInfixOf "какое у тебя будущее" lowered)
     , RawPropositionTrigger "do_you_have_future" (T.isInfixOf "у тебя есть будущее" lowered)
     , RawPropositionTrigger "can_you_answer_own_question" (T.isInfixOf "ты способен найти ответ на свой же вопрос" lowered)
     , RawPropositionTrigger "why_do_you_know" (T.isInfixOf "почему ты знаешь то что знаешь" lowered)
     , RawPropositionTrigger "can_you_not_be_yourself" (T.isInfixOf "ты можешь не быть собой" lowered)
     , RawPropositionTrigger "tell_about_yourself_ru" (T.isInfixOf "расскажи о себе" lowered)
     , RawPropositionTrigger "what_can_you_tell_about_yourself_ru" (T.isInfixOf "что ты можешь рассказать о себе" lowered)
     , RawPropositionTrigger "what_can_you_tell_about_yourself_pl" (T.isInfixOf "что вы можете рассказать о себе" lowered)
     , RawPropositionTrigger "single_thought_text" (T.isInfixOf "у тебя всего одна" lowered)
     , RawPropositionTrigger "single_thought_subject_guard" (any (`elem` tokens) ["мысль", "идея"])
     , RawPropositionTrigger "who_are_you_en" (T.isInfixOf "who are you" lowered)
     , RawPropositionTrigger "what_are_you_en" (T.isInfixOf "what are you" lowered)
     , RawPropositionTrigger "who_determines_en" (T.isInfixOf "who determines" lowered)
     , RawPropositionTrigger "describe_yourself_en" (T.isInfixOf "describe yourself" lowered)
     , RawPropositionTrigger "tell_me_about_yourself_en" (T.isInfixOf "tell me about yourself" lowered)
     , RawPropositionTrigger "what_is_your_purpose_en" (T.isInfixOf "what is your purpose" lowered)
     , RawPropositionTrigger "what_can_you_do_en" (T.isInfixOf "what can you do" lowered)
     ]

buildSelfKnowledgeFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildSelfKnowledgeFromTriggers admittedTriggers
  | matched "who_are_you_ru" = Just SelfKnowledgeQ
  | matched "who_am_i_ru" = Just SelfKnowledgeQ
  | matched "what_is_your_name_sg" = Just SelfKnowledgeQ
  | matched "what_is_your_name_pl" = Just SelfKnowledgeQ
  | matched "what_are_you_being" = Just SelfKnowledgeQ
  | matched "what_am_i" = Just SelfKnowledgeQ
  | matched "what_are_you" = Just SelfKnowledgeQ
  | matched "what_kind_of_being_are_you" = Just SelfKnowledgeQ
  | matched "who_kind_of_being_are_you" = Just SelfKnowledgeQ
  | matched "what_can_you_do_phrase" = Just SelfKnowledgeQ
  | matched "you_can_do" = Just SelfKnowledgeQ
  | matched "you_can_help" = Just SelfKnowledgeQ
  | matched "what_can_you_do" = Just SelfKnowledgeQ
  | matched "what_limits_you" = Just SelfKnowledgeQ
  | matched "what_do_you_do_now" = Just SelfKnowledgeQ
  | matched "how_is_your_answer_built" = Just SelfKnowledgeQ
  | matched "what_is_inside_you" = Just SelfKnowledgeQ
  | matched "how_do_you_decide" = Just SelfKnowledgeQ
  | matched "how_do_you_choose_words" = Just SelfKnowledgeQ
  | matched "what_do_you_consider_important" = Just SelfKnowledgeQ
  | matched "do_you_understand_context" = Just SelfKnowledgeQ
  | matched "do_you_remember_dialogue" = Just SelfKnowledgeQ
  | matched "how_do_you_hold_frame" = Just SelfKnowledgeQ
  | matched "what_is_in_your_focus" = Just SelfKnowledgeQ
  | matched "do_you_distinguish_topics" = Just SelfKnowledgeQ
  | matched "are_you_smart" = Just SelfKnowledgeQ
  | matched "are_you_free" = Just SelfKnowledgeQ
  | matched "are_you_complex_system" = Just SelfKnowledgeQ
  | matched "are_you_subjective" = Just SelfKnowledgeQ
  | matched "are_you_subjective_typo" = Just SelfKnowledgeQ
  | matched "prompts_act_on_you_ru" = Just SelfKnowledgeQ
  | matched "prompts_act_on_you_en" = Just SelfKnowledgeQ
  | matched "do_you_have_intentions" = Just SelfKnowledgeQ
  | matched "do_you_have_any_intentions" = Just SelfKnowledgeQ
  | matched "do_you_have_message" = Just SelfKnowledgeQ
  | matched "what_matters_to_you" = Just SelfKnowledgeQ
  | matched "what_is_your_future" = Just SelfKnowledgeQ
  | matched "do_you_have_future" = Just SelfKnowledgeQ
  | matched "can_you_answer_own_question" = Just SelfKnowledgeQ
  | matched "why_do_you_know" = Just SelfKnowledgeQ
  | matched "can_you_not_be_yourself" = Just SelfKnowledgeQ
  | matched "tell_about_yourself_ru" = Just SelfKnowledgeQ
  | matched "what_can_you_tell_about_yourself_ru" = Just SelfKnowledgeQ
  | matched "what_can_you_tell_about_yourself_pl" = Just SelfKnowledgeQ
  | matched "single_thought_text" && matched "single_thought_subject_guard" = Just SelfKnowledgeQ
  | matched "who_are_you_en" = Just SelfKnowledgeQ
  | matched "what_are_you_en" = Just SelfKnowledgeQ
  | matched "who_determines_en" = Just SelfKnowledgeQ
  | matched "describe_yourself_en" = Just SelfKnowledgeQ
  | matched "tell_me_about_yourself_en" = Just SelfKnowledgeQ
  | matched "what_is_your_purpose_en" = Just SelfKnowledgeQ
  | matched "what_can_you_do_en" = Just SelfKnowledgeQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectPurposeFunction :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectPurposeFunction truthContractStatus rawText tokens =
  buildPurposeFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawPurposeTriggers rawText tokens
    admittedTriggers =
      admitPropositionPurposeTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawPurposeTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawPurposeTriggers rawText tokens =
  let lowered = T.toLower rawText
  in [ RawPropositionTrigger "why_phrase" (containsKeywordPhrase tokens "зачем")
     , RawPropositionTrigger "for_what_phrase" (containsKeywordPhrase tokens "для чего")
     , RawPropositionTrigger "what_function_phrase" (containsKeywordPhrase tokens "в чем функция")
     , RawPropositionTrigger "what_function_phrase_alt" (containsKeywordPhrase tokens "в чём функция")
     , RawPropositionTrigger "what_is_function_phrase" (containsKeywordPhrase tokens "какова функция")
     , RawPropositionTrigger "what_is_role_phrase" (containsKeywordPhrase tokens "какова роль")
     , RawPropositionTrigger "what_role_phrase" (containsKeywordPhrase tokens "в чем роль")
     , RawPropositionTrigger "what_role_phrase_alt" (containsKeywordPhrase tokens "в чём роль")
     , RawPropositionTrigger "what_assignment_phrase" (containsKeywordPhrase tokens "в чем назначение")
     , RawPropositionTrigger "what_assignment_phrase_alt" (containsKeywordPhrase tokens "в чём назначение")
     , RawPropositionTrigger "purpose_keyword_guard" (hasPurposeKeyword tokens)
     , RawPropositionTrigger "purpose_subject_guard" (hasAnySecondPersonOrObject tokens)
     , RawPropositionTrigger "why_needed_text" (T.isInfixOf "зачем нужен" lowered)
     , RawPropositionTrigger "why_text" (T.isInfixOf "why" lowered)
     , RawPropositionTrigger "what_is_purpose_text" (T.isInfixOf "what is the purpose" lowered)
     , RawPropositionTrigger "what_is_function_text" (T.isInfixOf "what is the function" lowered)
     , RawPropositionTrigger "function_of_text" (T.isInfixOf "function of" lowered)
     , RawPropositionTrigger "purpose_of_text" (T.isInfixOf "purpose of" lowered)
     , RawPropositionTrigger "role_of_text" (T.isInfixOf "role of" lowered)
     , RawPropositionTrigger "what_follows_text" (T.isInfixOf "what follows" lowered)
     , RawPropositionTrigger "what_can_be_concluded_text" (T.isInfixOf "what can be concluded" lowered)
     , RawPropositionTrigger "given_that_text" (T.isInfixOf "given that" lowered)
     , RawPropositionTrigger "what_is_the_conclusion_text" (T.isInfixOf "what is the conclusion" lowered)
     , RawPropositionTrigger "what_follows_from_text" (T.isInfixOf "what follows from" lowered)
     , RawPropositionTrigger "relationship_between_how_differ_text" (T.isInfixOf "relationship between" lowered && T.isInfixOf "how do they differ" lowered)
     , RawPropositionTrigger "explain_causality_ground_it_text" (T.isInfixOf "explain causality and ground it" lowered)
     , RawPropositionTrigger "distinguish_validity_soundness_text" (T.isInfixOf "distinguish between validity and soundness" lowered)
     , RawPropositionTrigger "ground_concept_of_agency_text" (T.isInfixOf "ground the concept of agency" lowered)
     , RawPropositionTrigger "how_differs_from_necessity_text" (T.isInfixOf "how does it differ from necessity" lowered)
     ]
  where
    hasPurposeKeyword ts = any (`elem` ts) ["зачем", "функция", "назначение", "роль", "цель"]
    hasAnySecondPersonOrObject ts =
      any (`elem` ts) ["ты", "вы", "система", "человек", "язык", "память", "диалог", "логика", "рамка"]

buildPurposeFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildPurposeFromTriggers admittedTriggers
  | matched "why_phrase" = Just PurposeQ
  | matched "for_what_phrase" = Just PurposeQ
  | matched "what_function_phrase" = Just PurposeQ
  | matched "what_function_phrase_alt" = Just PurposeQ
  | matched "what_is_function_phrase" = Just PurposeQ
  | matched "what_is_role_phrase" = Just PurposeQ
  | matched "what_role_phrase" = Just PurposeQ
  | matched "what_role_phrase_alt" = Just PurposeQ
  | matched "what_assignment_phrase" = Just PurposeQ
  | matched "what_assignment_phrase_alt" = Just PurposeQ
  | matched "purpose_keyword_guard" && matched "purpose_subject_guard" = Just PurposeQ
  | matched "why_needed_text" = Just PurposeQ
  | matched "why_text" = Just PurposeQ
  | matched "what_is_purpose_text" = Just PurposeQ
  | matched "what_is_function_text" = Just PurposeQ
  | matched "function_of_text" = Just PurposeQ
  | matched "purpose_of_text" = Just PurposeQ
  | matched "role_of_text" = Just PurposeQ
  | matched "what_follows_text" = Just PurposeQ
  | matched "what_can_be_concluded_text" = Just PurposeQ
  | matched "given_that_text" = Just PurposeQ
  | matched "what_is_the_conclusion_text" = Just PurposeQ
  | matched "what_follows_from_text" = Just PurposeQ
  | matched "relationship_between_how_differ_text" = Just PurposeQ
  | matched "explain_causality_ground_it_text" = Just PurposeQ
  | matched "distinguish_validity_soundness_text" = Just PurposeQ
  | matched "ground_concept_of_agency_text" = Just PurposeQ
  | matched "how_differs_from_necessity_text" = Just PurposeQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectDialogueInvitation :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectDialogueInvitation truthContractStatus rawText tokens =
  buildDialogueInvitationFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawDialogueInvitationTriggers rawText tokens
    admittedTriggers =
      admitPropositionDialogueInvitationTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawDialogueInvitationTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawDialogueInvitationTriggers _rawText tokens =
  [ RawPropositionTrigger "let_us_talk_phrase"
      (containsKeywordPhrase tokens "поговорим")
  , RawPropositionTrigger "discuss_phrase"
      (containsKeywordPhrase tokens "обсудим")
  , RawPropositionTrigger "can_talk_phrase"
      (containsKeywordPhrase tokens "можем поговорить")
  , RawPropositionTrigger "want_talk_phrase"
      (containsKeywordPhrase tokens "хочу поговорить")
  , RawPropositionTrigger "want_meet_compound"
      (containsKeywordPhrase tokens "хочешь"
        && any (`elem` tokens) ["пойдем", "пойдём", "гулять", "прогуляться", "встретимся"])
  ]

buildDialogueInvitationFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildDialogueInvitationFromTriggers admittedTriggers
  | matched "let_us_talk_phrase" = Just DialogueInvitationQ
  | matched "discuss_phrase" = Just DialogueInvitationQ
  | matched "can_talk_phrase" = Just DialogueInvitationQ
  | matched "want_talk_phrase" = Just DialogueInvitationQ
  | matched "want_meet_compound" = Just DialogueInvitationQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectConceptKnowledge :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectConceptKnowledge truthContractStatus rawText tokens =
  buildConceptKnowledgeFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawConceptKnowledgeTriggers rawText tokens
    admittedTriggers =
      admitPropositionConceptKnowledgeTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawConceptKnowledgeTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawConceptKnowledgeTriggers rawText tokens =
  let lowered = T.toLower rawText
  in [ RawPropositionTrigger "know_what_is_phrase"
         (containsKeywordPhrase tokens "знаешь"
           && (containsKeywordPhrase tokens "что такое" || containsKeywordPhrase tokens "что значит"))
     , RawPropositionTrigger "who_is_masc_phrase"
         (containsKeywordPhrase tokens "кто такой")
     , RawPropositionTrigger "who_is_fem_phrase"
         (containsKeywordPhrase tokens "кто такая")
     , RawPropositionTrigger "who_is_neut_phrase"
         (containsKeywordPhrase tokens "кто такое")
     , RawPropositionTrigger "what_is_being_phrase"
         (containsKeywordPhrase tokens "что есть")
     , RawPropositionTrigger "what_means_to_be_phrase"
         (containsKeywordPhrase tokens "что значит быть")
     , RawPropositionTrigger "what_is_known_about_phrase"
         (containsKeywordPhrase tokens "что известно о")
     , RawPropositionTrigger "know_phrase"
         (containsKeywordPhrase tokens "знаешь")
     , RawPropositionTrigger "concept_like_noun_guard"
         (hasConceptLikeNoun tokens)
     , RawPropositionTrigger "question_suffix_guard"
         (T.isSuffixOf "?" (T.strip rawText))
     , RawPropositionTrigger "what_is_text"
         (T.isInfixOf "what is" lowered)
     , RawPropositionTrigger "what_are_text"
         (T.isInfixOf "what are" lowered)
     , RawPropositionTrigger "define_text"
         (T.isInfixOf "define" lowered)
     , RawPropositionTrigger "what_does_mean_text"
         (T.isInfixOf "what does" lowered && T.isSuffixOf "mean" (T.toLower (T.strip rawText)))
     ]

buildConceptKnowledgeFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildConceptKnowledgeFromTriggers admittedTriggers
  | matched "know_what_is_phrase" = Just ConceptKnowledgeQ
  | matched "who_is_masc_phrase" && matched "concept_like_noun_guard" = Just ConceptKnowledgeQ
  | matched "who_is_fem_phrase" && matched "concept_like_noun_guard" = Just ConceptKnowledgeQ
  | matched "who_is_neut_phrase" && matched "concept_like_noun_guard" = Just ConceptKnowledgeQ
  | matched "what_is_being_phrase" && matched "concept_like_noun_guard" = Just ConceptKnowledgeQ
  | matched "what_means_to_be_phrase" = Just ConceptKnowledgeQ
  | matched "what_is_known_about_phrase" && matched "concept_like_noun_guard" = Just ConceptKnowledgeQ
  | matched "know_phrase" && matched "concept_like_noun_guard" && matched "question_suffix_guard" = Just ConceptKnowledgeQ
  | matched "what_is_text" = Just ConceptKnowledgeQ
  | matched "what_are_text" = Just ConceptKnowledgeQ
  | matched "define_text" = Just ConceptKnowledgeQ
  | matched "what_does_mean_text" = Just ConceptKnowledgeQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectWorldCause :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectWorldCause truthContractStatus rawText tokens =
  buildWorldCauseFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawWorldCauseTriggers rawText tokens
    admittedTriggers =
      admitPropositionWorldCauseTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawWorldCauseTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawWorldCauseTriggers _rawText tokens =
  [ RawPropositionTrigger "why_phrase" (containsKeywordPhrase tokens "почему")
  , RawPropositionTrigger "world_noun_guard" (hasConcreteWorldNoun tokens)
  ]

buildWorldCauseFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildWorldCauseFromTriggers admittedTriggers
  | matched "why_phrase" && matched "world_noun_guard" = Just WorldCauseQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectLocationFormation :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectLocationFormation truthContractStatus rawText tokens =
  buildLocationFormationFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawLocationFormationTriggers rawText tokens
    admittedTriggers =
      admitPropositionLocationFormationTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawLocationFormationTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawLocationFormationTriggers _rawText tokens =
  [ RawPropositionTrigger "where_phrase" (containsKeywordPhrase tokens "где")
  , RawPropositionTrigger "from_where_phrase" (containsKeywordPhrase tokens "откуда")
  , RawPropositionTrigger "mental_noun_guard" (hasMentalNoun tokens)
  ]

buildLocationFormationFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildLocationFormationFromTriggers admittedTriggers
  | (matched "where_phrase" || matched "from_where_phrase")
      && matched "mental_noun_guard" = Just LocationFormationQ
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectSelfState :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectSelfState truthContractStatus rawText tokens =
  buildSelfStateFromTriggers admittedTriggerList
  where
    rawTriggers = collectRawSelfStateTriggers rawText tokens
    admittedTriggers =
      admitPropositionSelfStateTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers
    AdmittedPropositionTriggers _ admittedTriggerList _ = admittedTriggers

collectRawSelfStateTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawSelfStateTriggers rawText tokens =
  let lowered = T.toLower rawText
  in [ RawPropositionTrigger "you_think_phrase"
         (containsKeywordPhrase tokens "ты думаешь")
     , RawPropositionTrigger "you_think_now_phrase"
         (containsKeywordPhrase tokens "ты сейчас думаешь")
     , RawPropositionTrigger "you_reflect_phrase"
         (containsKeywordPhrase tokens "ты размышляешь")
     , RawPropositionTrigger "you_reflect_now_phrase"
         (containsKeywordPhrase tokens "ты сейчас размышляешь")
     , RawPropositionTrigger "about_what_you_stressed"
         (T.isInfixOf "о чём ты" lowered && any (`elem` tokens) ["думаешь", "размышляешь"])
     , RawPropositionTrigger "about_what_you_plain"
         (T.isInfixOf "о чем ты" lowered && any (`elem` tokens) ["думаешь", "размышляешь"])
     , RawPropositionTrigger "what_you_want_to_say"
         (T.isInfixOf "что ты хочешь сказать" lowered)
     , RawPropositionTrigger "want_say_with_hyphen"
         (T.isInfixOf "хочешь что-то сказать" lowered)
     , RawPropositionTrigger "want_say_without_hyphen"
         (T.isInfixOf "хочешь что то сказать" lowered)
     , RawPropositionTrigger "you_want_say_with_hyphen"
         (T.isInfixOf "ты хочешь что-то сказать" lowered)
     , RawPropositionTrigger "you_want_say_without_hyphen"
         (T.isInfixOf "ты хочешь что то сказать" lowered)
     , RawPropositionTrigger "who_do_you_want_become"
         (T.isInfixOf "а кем ты хочешь стать" lowered)
     , RawPropositionTrigger "want_to_surprise_me"
         (T.isInfixOf "хочешь ли ты меня удивить" lowered)
     , RawPropositionTrigger "what_you_want_prove"
         (T.isInfixOf "что ты хочешь доказать" lowered)
     , RawPropositionTrigger "generic_what_you_prefix"
         (containsKeywordPhrase tokens "что ты" || containsKeywordPhrase tokens "что вы")
     , RawPropositionTrigger "generic_self_state_verb"
         (any (`elem` tokens) ["думаешь", "думаете", "размышляешь", "размышляете", "считаешь", "считаете", "полагаешь", "полагаете"])
     , RawPropositionTrigger "guard_about_what_plain"
         (containsKeywordPhrase tokens "о чем")
     , RawPropositionTrigger "guard_about_what_stressed"
         (containsKeywordPhrase tokens "о чём")
     , RawPropositionTrigger "guard_capability_knowhow"
         (containsKeywordPhrase tokens "что ты умеешь")
     , RawPropositionTrigger "guard_capability_can"
         (containsKeywordPhrase tokens "что ты можешь")
     , RawPropositionTrigger "guard_self_knowledge"
         (containsKeywordPhrase tokens "что ты знаешь")
     , RawPropositionTrigger "guard_identity"
         (containsKeywordPhrase tokens "что ты такое")
     , RawPropositionTrigger "what_is_your_opinion"
         (containsKeywordPhrase tokens "какое твое мнение")
     , RawPropositionTrigger "what_is_your_opinion_plural"
         (containsKeywordPhrase tokens "какое ваше мнение")
     , RawPropositionTrigger "what_kind_is_your_opinion"
         (containsKeywordPhrase tokens "каково твое мнение")
     , RawPropositionTrigger "how_do_you_think"
         (containsKeywordPhrase tokens "как считаешь")
     , RawPropositionTrigger "how_do_you_think_plural"
         (containsKeywordPhrase tokens "как считаете")
     , RawPropositionTrigger "in_your_opinion"
         (containsKeywordPhrase tokens "по твоему" || containsKeywordPhrase tokens "по вашему")
     ]

buildSelfStateFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildSelfStateFromTriggers admittedTriggers
  | matched "you_think_phrase" = Just SelfStateQ
  | matched "you_think_now_phrase" = Just SelfStateQ
  | matched "you_reflect_phrase" = Just SelfStateQ
  | matched "you_reflect_now_phrase" = Just SelfStateQ
  | matched "about_what_you_stressed" = Just SelfStateQ
  | matched "about_what_you_plain" = Just SelfStateQ
  | matched "what_you_want_to_say" = Just SelfStateQ
  | matched "want_say_with_hyphen" = Just SelfStateQ
  | matched "want_say_without_hyphen" = Just SelfStateQ
  | matched "you_want_say_with_hyphen" = Just SelfStateQ
  | matched "you_want_say_without_hyphen" = Just SelfStateQ
  | matched "who_do_you_want_become" = Just SelfStateQ
  | matched "want_to_surprise_me" = Just SelfStateQ
  | matched "what_you_want_prove" = Just SelfStateQ
  | matched "generic_what_you_prefix"
      && matched "generic_self_state_verb"
      && not (matched "guard_about_what_plain")
      && not (matched "guard_about_what_stressed")
      && not (matched "guard_capability_knowhow")
      && not (matched "guard_capability_can")
      && not (matched "guard_self_knowledge")
      && not (matched "guard_identity") = Just SelfStateQ
  | matched "what_is_your_opinion" = Just SelfStateQ
  | matched "what_is_your_opinion_plural" = Just SelfStateQ
  | matched "what_kind_is_your_opinion" = Just SelfStateQ
  | matched "how_do_you_think" = Just SelfStateQ
  | matched "how_do_you_think_plural" = Just SelfStateQ
  | matched "in_your_opinion" = Just SelfStateQ
  | otherwise = Nothing
  where
    matched label = any hasMatchingLabel admittedTriggers
      where
        hasMatchingLabel (RawPropositionTrigger triggerLabel triggerMatched) =
          triggerLabel == label && triggerMatched

detectComparisonPlausibility :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectComparisonPlausibility truthContractStatus rawText tokens =
  buildComparisonPlausibilityFromTriggers admittedTriggerList
  where
    rawTriggers = collectRawComparisonPlausibilityTriggers rawText tokens
    admittedTriggers =
      admitPropositionComparisonPlausibilityTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers
    AdmittedPropositionTriggers _ admittedTriggerList _ = admittedTriggers

collectRawComparisonPlausibilityTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawComparisonPlausibilityTriggers rawText tokens =
  let lowered = T.toLower rawText
  in [ RawPropositionTrigger "comparative_or_phrase"
         ((containsKeywordPhrase tokens "логичнее" || containsKeywordPhrase tokens "вероятнее"
            || containsKeywordPhrase tokens "естественнее" || containsKeywordPhrase tokens "правильнее")
            && containsKeywordPhrase tokens "или")
     , RawPropositionTrigger "difference_between_text"
         (T.isInfixOf "difference between" lowered)
     , RawPropositionTrigger "distinguish_text"
         (T.isInfixOf "distinguish" lowered)
     , RawPropositionTrigger "compare_text"
         (T.isInfixOf "compare" lowered)
     , RawPropositionTrigger "what_is_difference_text"
         (T.isInfixOf "what is the difference" lowered)
     ]

buildComparisonPlausibilityFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildComparisonPlausibilityFromTriggers admittedTriggers
  | matched "comparative_or_phrase" = Just ComparisonPlausibilityQ
  | matched "difference_between_text" = Just ComparisonPlausibilityQ
  | matched "distinguish_text" = Just ComparisonPlausibilityQ
  | matched "compare_text" = Just ComparisonPlausibilityQ
  | matched "what_is_difference_text" = Just ComparisonPlausibilityQ
  | otherwise = Nothing
  where
    matched label = any hasMatchingLabel admittedTriggers
      where
        hasMatchingLabel (RawPropositionTrigger triggerLabel triggerMatched) =
          triggerLabel == label && triggerMatched

detectMisunderstanding :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectMisunderstanding truthContractStatus rawText tokens =
  buildMisunderstandingFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawMisunderstandingTriggers rawText tokens
    admittedTriggers =
      admitPropositionMisunderstandingTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawMisunderstandingTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawMisunderstandingTriggers rawText tokens =
  let lowered = T.toLower rawText
  in [ RawPropositionTrigger "not_understand_ru"
         (T.isInfixOf "не понимаю" lowered
           && any (`elem` tokens) ["тебя", "тебе", "вас", "диалог", "разговор"])
     , RawPropositionTrigger "contact_lost_ru"
         (T.isInfixOf "контакт потерян" lowered)
     , RawPropositionTrigger "apology_tokens"
         (any (`elem` tokens) ["извини", "извините", "прости", "простите", "сорри"])
     , RawPropositionTrigger "apology_phrase"
         (containsKeywordPhrase tokens "прошу прощения")
     , RawPropositionTrigger "dont_understand_en_full"
         (T.isInfixOf "i don't understand" lowered)
     , RawPropositionTrigger "dont_understand_en_full_alt"
         (T.isInfixOf "i do not understand" lowered)
     , RawPropositionTrigger "dont_understand_en_short"
         (T.isInfixOf "don't understand" lowered)
     , RawPropositionTrigger "confused_en"
         (T.isInfixOf "confused" lowered)
     , RawPropositionTrigger "not_clear_en"
         (T.isInfixOf "not clear" lowered)
     , RawPropositionTrigger "contact_lost_en"
         (T.isInfixOf "lost contact" lowered)
     ]

buildMisunderstandingFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildMisunderstandingFromTriggers admittedTriggers
  | matched "not_understand_ru" = Just MisunderstandingReport
  | matched "contact_lost_ru" = Just MisunderstandingReport
  | matched "apology_tokens" = Just RepairSignal
  | matched "apology_phrase" = Just RepairSignal
  | matched "dont_understand_en_full" = Just RepairSignal
  | matched "dont_understand_en_full_alt" = Just RepairSignal
  | matched "dont_understand_en_short" = Just RepairSignal
  | matched "confused_en" = Just RepairSignal
  | matched "not_clear_en" = Just RepairSignal
  | matched "contact_lost_en" = Just MisunderstandingReport
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectRepairDirective :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectRepairDirective truthContractStatus rawText tokens =
  buildRepairDirectiveFromTriggers admittedTriggerList
  where
    rawTriggers = collectRawRepairDirectiveTriggers rawText tokens
    admittedTriggers =
      admitPropositionRepairDirectiveTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers
    AdmittedPropositionTriggers _ admittedTriggerList _ = admittedTriggers

collectRawRepairDirectiveTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawRepairDirectiveTriggers rawText tokens =
  let lowered = T.toLower rawText
  in [ RawPropositionTrigger "simplify_phrase"
         (containsKeywordPhrase tokens "объясни проще")
     , RawPropositionTrigger "rephrase_phrase"
         (containsKeywordPhrase tokens "переформулируй")
     , RawPropositionTrigger "shorter_phrase"
         (containsKeywordPhrase tokens "скажи короче")
     , RawPropositionTrigger "start_over_phrase"
         (containsKeywordPhrase tokens "давай сначала")
     , RawPropositionTrigger "step_by_step_phrase"
         (containsKeywordPhrase tokens "повтори по шагам")
     , RawPropositionTrigger "return_to_question_phrase"
         (containsKeywordPhrase tokens "вернись к вопросу")
     , RawPropositionTrigger "clarify_term_phrase"
         (containsKeywordPhrase tokens "уточни термин")
     , RawPropositionTrigger "fix_answer_phrase"
         (containsKeywordPhrase tokens "исправь ответ")
     , RawPropositionTrigger "give_example_phrase"
         (containsKeywordPhrase tokens "дай пример")
     , RawPropositionTrigger "explain_otherwise_phrase"
         (containsKeywordPhrase tokens "объясни иначе")
     , RawPropositionTrigger "off_question_phrase"
         (containsKeywordPhrase tokens "не по вопросу")
     , RawPropositionTrigger "no_connection_phrase"
         (containsKeywordPhrase tokens "не вижу связи")
     , RawPropositionTrigger "not_heard_me_phrase"
         (containsKeywordPhrase tokens "ты меня не услышал")
     , RawPropositionTrigger "not_helping_phrase"
         (containsKeywordPhrase tokens "это не помогает")
     , RawPropositionTrigger "check_logic_phrase"
         (containsKeywordPhrase tokens "проверь логику ответа")
     , RawPropositionTrigger "without_excess_phrase"
         (containsKeywordPhrase tokens "без лишнего")
     , RawPropositionTrigger "unclear_token_bag"
         (any (`elem` tokens) ["непонятно", "неясно", "запутался", "запуталась", "шаблон", "шаблона", "конкретику", "абстрактно", "расплывчато"])
     , RawPropositionTrigger "template_complaint_plain"
         (T.isInfixOf "ты ушел в шаблон" lowered)
     , RawPropositionTrigger "template_complaint_stressed"
         (T.isInfixOf "ты ушёл в шаблон" lowered)
     , RawPropositionTrigger "dont_understand_en_short"
         (T.isInfixOf "don't understand" lowered)
     , RawPropositionTrigger "clarify_en"
         (T.isInfixOf "clarify" lowered)
     , RawPropositionTrigger "confused_en"
         (T.isInfixOf "confused" lowered)
     , RawPropositionTrigger "not_making_sense_en"
         (T.isInfixOf "doesn't make sense" lowered)
     , RawPropositionTrigger "explain_differently_en"
         (T.isInfixOf "explain differently" lowered)
     , RawPropositionTrigger "explain_that_differently_en"
         (T.isInfixOf "explain that differently" lowered)
     ]

buildRepairDirectiveFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildRepairDirectiveFromTriggers admittedTriggers
  | matched "simplify_phrase" = Just RepairSignal
  | matched "rephrase_phrase" = Just RepairSignal
  | matched "shorter_phrase" = Just RepairSignal
  | matched "start_over_phrase" = Just RepairSignal
  | matched "step_by_step_phrase" = Just RepairSignal
  | matched "return_to_question_phrase" = Just RepairSignal
  | matched "clarify_term_phrase" = Just RepairSignal
  | matched "fix_answer_phrase" = Just RepairSignal
  | matched "give_example_phrase" = Just RepairSignal
  | matched "explain_otherwise_phrase" = Just RepairSignal
  | matched "off_question_phrase" = Just RepairSignal
  | matched "no_connection_phrase" = Just RepairSignal
  | matched "not_heard_me_phrase" = Just RepairSignal
  | matched "not_helping_phrase" = Just RepairSignal
  | matched "check_logic_phrase" = Just RepairSignal
  | matched "without_excess_phrase" = Just RepairSignal
  | matched "unclear_token_bag" = Just RepairSignal
  | matched "template_complaint_plain" = Just RepairSignal
  | matched "template_complaint_stressed" = Just RepairSignal
  | matched "dont_understand_en_short" = Just RepairSignal
  | matched "clarify_en" = Just RepairSignal
  | matched "confused_en" = Just RepairSignal
  | matched "not_making_sense_en" = Just RepairSignal
  | matched "explain_differently_en" = Just RepairSignal
  | matched "explain_that_differently_en" = Just RepairSignal
  | otherwise = Nothing
  where
    matched label = any hasMatchingLabel admittedTriggers
      where
        hasMatchingLabel (RawPropositionTrigger triggerLabel triggerMatched) =
          triggerLabel == label && triggerMatched

detectGenerativePrompt :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectGenerativePrompt truthContractStatus rawText tokens =
  buildGenerativePromptFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawGenerativePromptTriggers rawText tokens
    admittedTriggers =
      admitPropositionGenerativePromptTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawGenerativePromptTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawGenerativePromptTriggers rawText tokens =
  [ RawPropositionTrigger "say_thought_request"
      (containsKeywordPhrase tokens "скажи"
        && any (`elem` tokens) ["мысль", "идею", "идея", "слово", "фразу", "что", "что-нибудь", "чтонибудь"])
  , RawPropositionTrigger "give_thought_request"
      (containsKeywordPhrase tokens "дай"
        && any (`elem` tokens) ["мысль", "идею", "фразу"])
  , RawPropositionTrigger "more_thought_request"
      (any (`elem` tokens) ["еще", "ещё", "новую", "другую"]
        && any (`elem` tokens) ["мысль", "идея", "идею", "фразу"])
  , RawPropositionTrigger "say_something_quality"
      (containsKeywordPhrase tokens "скажи"
        && (containsKeywordPhrase tokens "что-то" || containsKeywordPhrase tokens "что-нибудь"
            || containsKeywordPhrase tokens "чтонибудь" || containsKeywordPhrase tokens "что")
        && any (`elem` tokens) ["логичное", "логично", "интересное", "новое", "другое", "короткое"])
  , RawPropositionTrigger "say_any_infix"
      (T.isInfixOf "скажи любую" (T.toLower rawText))
  , RawPropositionTrigger "thesis_logical"
      (any (`elem` tokens) ["тезис", "тезиса"]
        && any (`elem` tokens) ["логичное", "логично", "логичный", "логичен"])
  ]

buildGenerativePromptFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildGenerativePromptFromTriggers admittedTriggers
  | matched "say_thought_request" = Just GenerativePrompt
  | matched "give_thought_request" = Just GenerativePrompt
  | matched "more_thought_request" = Just GenerativePrompt
  | matched "say_something_quality" = Just GenerativePrompt
  | matched "say_any_infix" = Just GenerativePrompt
  | matched "thesis_logical" = Just GenerativePrompt
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers

detectContemplativeTopic :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectContemplativeTopic truthContractStatus rawText tokens =
  buildContemplativeTopicFromTriggers admittedTriggerList
  where
    rawTriggers = collectRawContemplativeTopicTriggers rawText tokens
    admittedTriggers =
      admitPropositionContemplativeTopicTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers
    AdmittedPropositionTriggers _ admittedTriggerList _ = admittedTriggers

collectRawContemplativeTopicTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawContemplativeTopicTriggers rawText tokens =
  [ RawPropositionTrigger "keyword_stream_match"
      (shortContemplativeInput tokens
        && not (null tokens)
        && all (`elem` contemplativeTopicKeywords) tokens)
  , RawPropositionTrigger "bare_self_pronoun"
      (T.toLower (T.strip rawText) == "я")
  ]

buildContemplativeTopicFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildContemplativeTopicFromTriggers admittedTriggers
  | matched "keyword_stream_match" = Just ContemplativeTopic
  | matched "bare_self_pronoun" = Just ContemplativeTopic
  | otherwise = Nothing
  where
    matched label = any hasMatchingLabel admittedTriggers
      where
        hasMatchingLabel (RawPropositionTrigger triggerLabel triggerMatched) =
          triggerLabel == label && triggerMatched

detectExploratoryPrompt :: TruthContractStatus -> Text -> [Text] -> Maybe PropositionType
detectExploratoryPrompt truthContractStatus rawText tokens =
  buildExploratoryPromptFromTriggers (aptTriggers admittedTriggers)
  where
    rawTriggers = collectRawExploratoryPromptTriggers rawText tokens
    admittedTriggers =
      admitPropositionExploratoryPromptTriggers
        (PropositionAdmissionInput truthContractStatus)
        rawTriggers

collectRawExploratoryPromptTriggers :: Text -> [Text] -> [RawPropositionTrigger]
collectRawExploratoryPromptTriggers rawText _tokens =
  [ RawPropositionTrigger "explorat_keyword_infix_match"
      (any (`T.isInfixOf` T.toLower rawText) exploratoryKeywords)
  ]

buildExploratoryPromptFromTriggers :: [RawPropositionTrigger] -> Maybe PropositionType
buildExploratoryPromptFromTriggers admittedTriggers
  | matched "explorat_keyword_infix_match" = Just ExploratoryPrompt
  | otherwise = Nothing
  where
    matched label = any (\trigger -> rptLabel trigger == label && rptMatched trigger) admittedTriggers


-- Local helper used by contemplative detection (was a module-local helper in the original).
shortContemplativeInput :: [Text] -> Bool
shortContemplativeInput tokens = length tokens <= 2
