{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-|
Unified meaning atoms for QxFx0 dialog assembly.

All text generation — facts, acknowledgements, stance, contact, recovery —
is expressed as a combination of:
  1. Decomposed atoms  (this module)
  2. Assembly operations (DialogAssembly)
  3. Planner — selects operations from available atoms

No pre-written templates. Text is generated by function composition over atoms.
-}
module QxFx0.Semantic.DialogAtom
  ( -- * Unified atom tag
    AtomTag(..)
    -- * Slot value
  , AtomSlot(..)
    -- * Dialog context: atoms for the current turn
  , DialogAtoms(..)
  , emptyDialogAtoms
  , daTopicNominative
  , daTopicGenitive
  , daTopicPrepositional
  , daTopicAccusative
    -- * Constructors
  , plainSlot
  , nounSlot
  , pronoun
  , atomValue
  , atomValues
  , hasTag
  , headAtomValue
  ) where

import Control.DeepSeq (NFData)
import Data.Aeson (FromJSON(..), ToJSON(..), FromJSONKey(..), FromJSONKeyFunction(..), ToJSONKey(..), ToJSONKeyFunction(..))
import Text.Read (readMaybe)
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as M
import Data.Text (Text)
import qualified Data.Text as T
import GHC.Generics (Generic)

--------------------------------------------------------------------------------
-- Atom tags — unified across facts AND dialog
--------------------------------------------------------------------------------

{-| Semantic tag for any piece of information in the turn context.

  Split into three families:
  - Factual: subject, properties, quantities, mechanisms — from knowledge base
  - Dialog: user intent, contact state, phase, stance — from turn routing
  - Meta: identity, constraints, goals — from system state
-}
data AtomTag
  -- Fact atoms (from knowledge decomposition)
  = TSubject          -- ^ Entity under discussion
  | TProperty         -- ^ Attribute/quality
  | TQuantity         -- ^ Numeric value
  | TUnit             -- ^ Unit of measurement
  | TPeriod           -- ^ Time frame
  | TEffect           -- ^ Result/consequence
  | TMechanism        -- ^ How it works
  | TContext          -- ^ Broader system/framework
  | TRelation         -- ^ Connection to other concepts
  | TScale            -- ^ Comparison reference
  | TLocation         -- ^ Where
  | TDiscoverer       -- ^ Who/first described
  | TYear             -- ^ When (historical)
  | TReason           -- ^ Why it matters
    -- Dialog atoms (from routing + proposition classification)
  | TUserIntent       -- ^ What user wants: define, clarify, ground, reflect, complain...
  | TTopic            -- ^ Subject of conversation (word/phrase)
  | TStance           -- ^ System stance: firm, tentative, honest, exploratory
  | TEmotion          -- ^ Emotional tone: distress, curious, hopeful, confrontational
  | TKnowledge        -- ^ Epistemic status: known, probable, uncertain, unknown
  | TPhase            -- ^ Dialogue phase: opening, deepening, anchoring, repair, closing
  | TTurnGoal         -- ^ What this turn aims to achieve
    -- Meta atoms (from system state)
  | TIdentity         -- ^ System self-description
  | TConstraint       -- ^ Limitation / boundary
  | TCapability       -- ^ What the system can do
  | TGreeting         -- ^ Smalltalk / contact initiation
  | TFarewell         -- ^ Ending interaction
  | TConnector        -- ^ Discourse linker: "кстати", "впрочем", "более того"
  | THedge            -- ^ Hedging softener: "как бы", "в некотором смысле", "пожалуй"
  | TSoftener         -- ^ Tone softener: "если хочешь", "может быть", "давай попробуем"
  | TModifier         -- ^ Adverbial/adjectival modifier from input: "коротко", "подробно", "только", "ещё"
   | TAgreement      -- ^ Agreement signal: "верно", "совершенно верно", "именно так"
   | TDisagreement   -- ^ Disagreement signal: "не совсем", "я бы поспорил", "это не так"
   | TRelatedTopic   -- ^ Related topic for natural transitions: "кстати о сосудах..."
   | TModal          -- ^ Modal particle: "ведь", "же", "разве", "всё-таки", "вообще-то"
   | TFiller         -- ^ Conversational filler: "ну", "так", "значит", "слушай", "смотри", "понимаешь"
   | TNumber          -- ^ Cardinal/ordinal: "три", "первый", "оба", "несколько"
   | TQuantifier      -- ^ "все", "каждый", "любой", "некоторые", "многие", "ни один", "большинство"
   | TEmphatic        -- ^ "именно", "даже", "просто", "всего лишь", "хотя бы"

  deriving stock (Eq, Ord, Show, Generic, Bounded, Enum, Read)
  deriving anyclass (NFData, ToJSON, FromJSON)

instance ToJSONKey AtomTag where
  toJSONKey = ToJSONKeyValue toJSON toEncoding
instance FromJSONKey AtomTag where
  fromJSONKey = FromJSONKeyTextParser $ \t ->
    case readMaybe (T.unpack t) of
      Just tag -> pure tag
      Nothing  -> fail ("Unknown AtomTag: " ++ T.unpack t)

--------------------------------------------------------------------------------
-- AtomSlot — a tagged value with full morphological forms
--------------------------------------------------------------------------------

{-| One atom slot = tag + text value + 5 Russian case forms + plural. -}
data AtomSlot = AtomSlot
  { asTag     :: !AtomTag
  , asValue   :: !Text          -- ^ Primary form (nominative or raw)
  , asGen     :: !Text          -- ^ Genitive
  , asPrep    :: !Text          -- ^ Prepositional
  , asAcc     :: !Text          -- ^ Accusative
  , asIns     :: !Text          -- ^ Instrumental
  , asPlural  :: !Text          -- ^ Plural nominative
  } deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData, ToJSON, FromJSON)

{-| Slot with no morphological variation (numbers, raw text). -}
plainSlot :: AtomTag -> Text -> AtomSlot
plainSlot tag val = AtomSlot tag val val val val val val

{-| Slot with full 5-case Russian noun forms. -}
nounSlot :: AtomTag -> Text -> Text -> Text -> Text -> Text -> Text -> AtomSlot
nounSlot = AtomSlot

--------------------------------------------------------------------------------
-- DialogAtoms — the full state of one turn
--------------------------------------------------------------------------------

{-| All atoms available for a single turn assembly.

  Populated from:
  - InputPropositionFrame (user intent, topic, emotion)
  - CanonicalMoveFamily + StanceMarker (system stance)
  - SystemState (identity, phase, turn count)
  - Knowledge base lookup (factual atoms if a known topic)
-}
data DialogAtoms = DialogAtoms
  { daSlots :: !(Map AtomTag [AtomSlot])
    -- ^ All slots, possibly multiple per tag
  , daUserRaw :: !Text
    -- ^ Original user input (for seed/hash/pickDeterministic)
  , daTurn :: !Int
    -- ^ Turn index in this session
  } deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData, ToJSON, FromJSON)

emptyDialogAtoms :: DialogAtoms
emptyDialogAtoms = DialogAtoms M.empty "" 0

--------------------------------------------------------------------------------
-- Convenience accessors
--------------------------------------------------------------------------------

daTopicNominative :: DialogAtoms -> Text
daTopicNominative  = headAtomValue TTopic

daTopicGenitive :: DialogAtoms -> Text
daTopicGenitive da = case M.lookup TTopic (daSlots da) of
  Just (s:_) -> asGen s; _ -> "темы"

daTopicPrepositional :: DialogAtoms -> Text
daTopicPrepositional da = case M.lookup TTopic (daSlots da) of
  Just (s:_) -> asPrep s; _ -> "теме"

daTopicAccusative :: DialogAtoms -> Text
daTopicAccusative da = case M.lookup TTopic (daSlots da) of
  Just (s:_) -> asAcc s; _ -> "тему"

atomValue :: AtomTag -> DialogAtoms -> [AtomSlot]
atomValue tag (DialogAtoms m _ _) = M.findWithDefault [] tag m

atomValues :: AtomTag -> DialogAtoms -> [Text]
atomValues tag = map asValue . atomValue tag

hasTag :: AtomTag -> DialogAtoms -> Bool
hasTag tag = not . null . atomValue tag

headAtomValue :: AtomTag -> DialogAtoms -> Text
headAtomValue tag da = case atomValue tag da of
  (s:_) -> asValue s; [] -> ""

{-| Pick the correct Russian 3rd-person pronoun for a subject. -}
pronoun :: Text -> Text
pronoun w =
  let w' = T.toLower (T.strip w)
  in case M.lookup w' genderDict of
       Just p -> p
       Nothing ->
         if " " `T.isInfixOf` w'
           then "они"
           else case T.unsnoc w' of
                  Just (_, 'а') | not ("мя" `T.isSuffixOf` w') -> "она"
                  Just (_, 'я') -> "она"
                  Just (_, 'о') -> "оно"
                  Just (_, 'е') -> "оно"
                  Just (_, 'ь') -> "она"
                  _ -> "он"

genderDict :: Map Text Text
genderDict = M.fromList
  [("сердце","оно"),("аорта","она"),("сосуды","он"),("кровеносные сосуды","он"),("группы крови","он"),("кровь","она"),("артерия","она"),("печень","она"),("скорость","она"),("закон","он"),("атом","он"),("вода","она"),("таблица","она"),("элемент","он"),("теория","она"),("клетка","она"),("митохондрия","она"),("число","оно"),("теорема","она"),("возраст","он"),("солнце","оно"),("дыра","она"),("гора","она"),("точка","она"),("озеро","оно"),("римская","она"),("революция","она"),("война","она"),("право","оно"),("хартия","она"),("презумпция","она"),("адам","он"),("валова","она"),("инфляция","она"),("алан","он"),("компьютер","он"),("интернет","он"),("мир","он"),("язык","он"),("санскрит","он"),("зигмунд","он"),("эксперимент","он"),("диссонанс","он"),("роман","он"),("комедия","она"),("мигель","она"),("леонардо","оно"),("импрессионизм","он"),("пабло","оно"),("иоганн","он"),("вольфганг","он"),("людвиг","он"),("сократ","он"),("критика","она"),("аристотель","она"),("христианство","оно"),("ислам","он"),("индуизм","он"),("демократия","она"),("организация","она"),("разделение","оно"),("огюст","он"),("макс","он"),("эмиль","она")]

