{-# LANGUAGE OverloadedStrings #-}

module QxFx0.Bridge.EmbeddedSQLSync
  ( embeddedSqlGeneratedMarker
  , renderEmbeddedSqlModule
  , checkEmbeddedSqlSync
  , writeEmbeddedSqlModule
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import QxFx0.Resources.Paths (ResourcePaths(..))
import System.Directory (doesFileExist)

embeddedSqlGeneratedMarker :: Text
embeddedSqlGeneratedMarker = "-- Generated by qxfx0 --sync-embedded-sql from spec/sql."

renderEmbeddedSqlModule :: ResourcePaths -> IO Text
renderEmbeddedSqlModule paths = do
  schemaSql <- TIO.readFile (rpSchemaSql paths)
  seedClusters <- TIO.readFile (rpSeedClusters paths)
  seedTemplates <- TIO.readFile (rpSeedTemplates paths)
  seedIdentity <- TIO.readFile (rpSeedIdentity paths)
  pure $ T.unlines
    [ "{-# LANGUAGE OverloadedStrings #-}"
    , "{-# LANGUAGE StrictData #-}"
    , "module QxFx0.Bridge.EmbeddedSQL"
    , "  ( schemaSQL"
    , "  , seedClustersSQL"
    , "  , seedTemplatesSQL"
    , "  , seedIdentitySQL"
    , "  ) where"
    , ""
    , "import Data.Text (Text)"
    , "import qualified Data.Text as T"
    , ""
    , embeddedSqlGeneratedMarker
    , renderBinding "schemaSQL" schemaSql
    , ""
    , renderBinding "seedClustersSQL" seedClusters
    , ""
    , renderBinding "seedTemplatesSQL" seedTemplates
    , ""
    , renderBinding "seedIdentitySQL" seedIdentity
    ]

checkEmbeddedSqlSync :: ResourcePaths -> FilePath -> IO (Either Text ())
checkEmbeddedSqlSync paths modulePath = do
  expected <- renderEmbeddedSqlModule paths
  exists <- doesFileExist modulePath
  if not exists
    then pure (Left "EmbeddedSQL.hs is missing")
    else do
      current <- TIO.readFile modulePath
      pure $
        if embeddedSqlGeneratedMarker `T.isInfixOf` current
          then
            if current == expected
              then Right ()
              else Left "EmbeddedSQL.hs is out of sync with spec/sql"
          else Left "EmbeddedSQL.hs is missing generated marker; file must be generated, not edited manually"

writeEmbeddedSqlModule :: ResourcePaths -> FilePath -> IO ()
writeEmbeddedSqlModule paths modulePath =
  renderEmbeddedSqlModule paths >>= TIO.writeFile modulePath

renderBinding :: Text -> Text -> Text
renderBinding binding content =
  T.unlines
    [ binding <> " :: Text"
    , binding <> " = T.pack " <> haskellStringLiteral content
    ]

haskellStringLiteral :: Text -> Text
haskellStringLiteral text = T.pack (show (T.unpack text))
