-- AUTO-GENERATED by scripts/export_lexicon.py from spec/sql/lexicon.
-- Canonical direction: SQL -> GF syntax scaffold (do not edit this file manually).
abstract QxFx0Syntax = QxFx0Lexicon ** {
  flags startcat = Move ;

  cat
    Move ;
    NP ;
    VP ;
    GfNumber ;
    Modifier ;
    Relation ;
    Mechanism ;
    ActTopic ;

  fun
    NumSg : GfNumber ;
    NumPl : GfNumber ;

    MkNP : Lexeme -> NP ;

    ActMaintain : GfNumber -> Lexeme -> VP ;
    ActDefine   : Lexeme -> VP ;

    ModFirst    : Modifier ;
    ModStrictly : Modifier ;

    MoveInvite : NP -> Modifier -> VP -> Move ;
    MoveDefine : NP -> Relation -> NP -> Move ;
    MoveCause  : NP -> Mechanism -> Move ;
    MovePurpose : NP -> Move ;
    MoveSelfState : Move ;
    MoveCompare : NP -> NP -> Move ;
    MoveOperationalStatus : Move ;
    MoveOperationalCause : Move ;
    MoveSystemLogic : Move ;
    MoveMisunderstanding : Move ;
    MoveGenerativeThought : Move ;
    MoveContemplative : NP -> Move ;
    MoveGround : NP -> Move ;
    MoveContact : NP -> Move ;
    MoveReflect : NP -> Move ;
    MoveDescribe : NP -> Move ;
    MoveDeepen : NP -> Move ;
    MoveConfront : NP -> Move ;
    MoveAnchor : NP -> Move ;
    MoveClarify : NP -> Move ;
    MoveNextStepLocal : NP -> Move ;
    MoveHypothesis : NP -> Move ;
    MoveDistinguish : NP -> NP -> Move ;

    RelIdentity : Relation ;
    MechParse   : Mechanism ;

    ActAnswer    : ActTopic ;
    ActQuestion  : ActTopic ;
    ActTopicTerm : ActTopic ;
    ActProject   : ActTopic ;
    ActResult    : ActTopic ;

    MoveActOnTopic : ActTopic -> Move ;

    ApplyStanceTentative : Move -> Move ;
    ApplyStanceFirm      : Move -> Move ;
}
