#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "src" / "QxFx0" / "Bridge" / "EmbeddedSQL.hs"
GENERATED_MARKER = "-- Generated by scripts/sync_embedded_sql.py from spec/sql."
SQL_FILES = {
    "schemaSQL": ROOT / "spec" / "sql" / "schema.sql",
    "seedClustersSQL": ROOT / "spec" / "sql" / "seed_clusters.sql",
    "seedTemplatesSQL": ROOT / "spec" / "sql" / "seed_templates.sql",
    "seedIdentitySQL": ROOT / "spec" / "sql" / "seed_identity.sql",
}


def haskell_string_literal(text: str) -> str:
    return (
        '"'
        + (
            text.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\t", "\\t")
        )
        + '"'
    )


def render_module() -> str:
    header = (
        """{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}
module QxFx0.Bridge.EmbeddedSQL
  ( schemaSQL
  , seedClustersSQL
  , seedTemplatesSQL
  , seedIdentitySQL
  ) where

import Data.Text (Text)
import qualified Data.Text as T

"""
        + GENERATED_MARKER
        + """
"""
    )
    body_parts = []
    for binding, path in SQL_FILES.items():
        content = path.read_text(encoding="utf-8")
        body_parts.append(
            f"{binding} :: Text\n{binding} = T.pack {haskell_string_literal(content)}\n"
        )
    return header + "\n".join(body_parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Fail if EmbeddedSQL.hs is out of sync"
    )
    args = parser.parse_args()

    rendered = render_module()
    schema_sql = SQL_FILES["schemaSQL"].read_text(encoding="utf-8")
    if args.check:
        current = (
            MODULE_PATH.read_text(encoding="utf-8") if MODULE_PATH.exists() else ""
        )
        if GENERATED_MARKER not in current:
            print(
                "EmbeddedSQL.hs is missing generated marker; file must be generated, not edited manually",
                file=sys.stderr,
            )
            return 1
        if current != rendered:
            print(
                "EmbeddedSQL.hs is out of sync with spec/sql (edit spec/sql and rerun scripts/sync_embedded_sql.py)",
                file=sys.stderr,
            )
            return 1
        print("EmbeddedSQL.hs is in sync with spec/sql")
        return 0

    MODULE_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {MODULE_PATH}")
    return 0

    MODULE_PATH.write_text(rendered, encoding="utf-8")
    MIGRATION_PATH.write_text(schema_sql, encoding="utf-8")
    print(f"wrote {MODULE_PATH}")
    print(f"wrote {MIGRATION_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
