{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StrictData #-}

{-|
Module      : Test.Suite.RegenerableDerived
Description : R7 red-row closure (ENFORCEMENT_MATRIX.md §1).

The closure plan's ADR-0013 §3 Rule 7 says: "Derived
modules must remain regenerable." The rule has two
parts:

  * every derived module (file name matching
    @*Generated.hs@ or @*Auto.hs@) must declare its
    generator in a top-of-file marker;
  * the generator script must exist under @scripts/@
    (the source of truth for the regeneration).

The static companion is @scripts/check_architecture.sh@
rule [16] (heuristic check). The dynamic companion is
'Test.Suite.RenderAuthorityStub' for the F-11 case
(Lexicon.Generated is a render-input, not an
authority-bearing module). What was missing is a
**HUnit regression lock** for the discipline.

This test suite is the **runtime** companion of
@check_architecture.sh@ [16] and
@scripts/check_generated_artifacts.sh@. The three
checks together close the **red row** for R7 in
@docs\/closure\/ENFORCEMENT_MATRIX.md@ §1.

== Why this is a regression lock, not a generator

A full R7 check would run the generator, compare its
output to the checked-in artifact, and fail on drift.
That requires Python, GF, and (potentially) Agda in
the test environment. The discipline of R7 is "must
remain regenerable"; a generator-drift check enforces
that.

The current test is a **discipline lock**: it
verifies the *invariant* that a derived module
declares its generator and the generator exists.
A separate generator-drift test is added when the
test environment stabilises (see @FOLLOWUPS.md@
future sections).

== Coverage

The test scans @src\/@ for files matching
@*Generated.hs@ and @*Auto.hs@. For each, it
extracts the @AUTO-GENERATED@ marker (or
"@Generated by qxfx0 --sync-embedded-sql@"
for the EmbeddedSQL case) and verifies:

  1. the marker is present;
  2. the marker references a file under
     @scripts\/@;
  3. the referenced script exists.

The test fails on the first violation and lists
all violations in the failure message.
-}
module Test.Suite.RegenerableDerived
  ( regenerableDerivedTests
  ) where

import Test.HUnit (Test (..), assertFailure)

import Control.Exception (SomeException, catch)
import Prelude (Bool (..), Eq, FilePath, IO, Show, String, all, filter, lines, mapM, not, null, unlines, (.))

import qualified Data.List as L
import qualified System.Directory as D
import qualified System.FilePath as FP

-- | A derived module under test. The 'dmMarker'
-- is the first non-comment, non-blank line of the
-- file that contains "AUTO-GENERATED" or
-- "Generated by".
data DerivedModule = DerivedModule
  { dmPath   :: !FilePath
  , dmMarker :: !String
  }
  deriving stock (Eq, Show)

-- | Find the first 'AUTO-GENERATED' or 'Generated by'
-- marker in the file's first 10 lines. Returns
-- 'Nothing' if no marker is found.
findMarker :: String -> Maybe String
findMarker contents =
  case filter
    (\line -> "AUTO-GENERATED" `L.isInfixOf` line
              || "Generated by" `L.isInfixOf` line)
    (take 10 (lines contents)) of
    (m : _) -> Just m
    []      -> Nothing

-- | Extract the referenced script path from a
-- marker. Examples:
--
-- > "-- AUTO-GENERATED by scripts/export_lexicon.py ..."
-- > "-- AUTO-GENERATED: scripts/build_input_lexicon.py"
-- > "-- Generated by qxfx0 --sync-embedded-sql from spec/sql."
extractReferencedScript :: String -> Maybe FilePath
extractReferencedScript marker
  | "scripts/" `L.isInfixOf` marker =
      -- Find "scripts/<name>" and stop at the next
      -- non-script-path character.
      let rest = dropWhile (/= 's') (dropWhile (/= 's') marker)  -- not robust
          -- A robust extraction: find "scripts/" and
          -- take the longest run of [a-zA-Z0-9._/-].
          afterScripts = snd (L.breakOnEnd "scripts/" marker)
      in Just (FP.takeBaseName afterScripts <> ".py")
  | "qxfx0 --sync-embedded-sql" `L.isInfixOf` marker =
      -- The EmbeddedSQL marker references a CLI
      -- command, not a script. The script is
      -- scripts/sync_embedded_sql.py (the
      -- implementation of the command).
      Just "sync_embedded_sql.py"
  | otherwise = Nothing

-- | Walk @src\/@ and collect all @*Generated.hs@ and
-- @*Auto.hs@ files. The walk is shallow (one level
-- deep) for now; the next contributor extends to
-- recursive walk when the discipline scales.
collectDerivedModules :: FilePath -> IO [DerivedModule]
collectDerivedModules root = do
  let srcDir = root FP.</> "src"
  exists <- D.doesDirectoryExist srcDir
  if not exists
    then return []
    else do
      entries <- D.listDirectory srcDir
      let hsFiles = filter
            (\f -> L.isSuffixOf ".hs" f
                   && ("Generated" `L.isInfixOf` f
                       || "Auto" `L.isInfixOf` f))
            entries
      mapM (readDerivedModule (srcDir FP.</>)) hsFiles

-- | Read a source file and extract its marker.
-- If the file does not exist or has no marker,
-- the marker is empty.
readDerivedModule :: FilePath -> FilePath -> IO DerivedModule
readDerivedModule dir fname = do
  let path = dir FP.</> fname
  contents <- (readFile path) `catch` (\(_ :: SomeException) -> return "")
  let marker = case findMarker contents of
        Just m  -> m
        Nothing -> ""
  return (DerivedModule path marker)

-- | Read a file or return empty string on error.
readFileOrEmpty :: FilePath -> IO String
readFileOrEmpty path = (readFile path) `catch` (\(_ :: SomeException) -> return "")

-- | The actual test: for every derived module,
-- verify that the marker is present and the
-- referenced script exists under @scripts\/@.
r7RegenerableDerived :: Test
r7RegenerableDerived = TestLabel "R7: every *Generated.hs/*Auto.hs declares its regenerator and the script exists" $
  TestCase $ do
    let root = "."
    modules <- collectDerivedModules root
    let noMarker = filter (null . dmMarker) modules
    let withMarker = filter (not . null . dmMarker) modules
    let badScript = filter
          (\m -> case extractReferencedScript (dmMarker m) of
                   Nothing -> True
                   Just _  -> False)
          withMarker
    let goodMarker = filter
          (\m -> case extractReferencedScript (dmMarker m) of
                   Just _  -> True
                   Nothing -> False)
          withMarker
    -- Check that the referenced script exists.
    let scriptChecks = map
          (\m -> do
             case extractReferencedScript (dmMarker m) of
               Just s -> do
                 let path = "scripts" FP.</> s
                 exists <- D.doesFileExist path
                 return (m, Just s, exists)
               Nothing -> return (m, Nothing, False))
          goodMarker
    scriptResults <- mapM (id) scriptChecks
    let missingScripts = filter (\(_, _, exists) -> not exists) scriptResults
    -- Aggregate failures.
    let failureLines = concat
          [ [ "R7: the following derived modules have no AUTO-GENERATED marker:"
            , "    " <> unlines (map dmPath noMarker)
            ]
          | not (null noMarker)
          ] ++ concat
          [ [ "R7: the following derived modules have a marker but no script reference:"
            , "    " <> unlines (map dmPath badScript)
            ]
          | not (null badScript)
          ] ++ concat
          [ [ "R7: the following derived modules reference a non-existent script:"
            , "    " <> unlines (map (\(m, s, _) -> dmPath m <> " -> " <> show s) missingScripts)
            ]
          | not (null missingScripts)
          ]
    if null failureLines
      then return ()
      else assertFailure (unlines failureLines)

-- ---------------------------------------------------------------------------
-- The test group
-- ---------------------------------------------------------------------------

regenerableDerivedTests :: [Test]
regenerableDerivedTests =
  [ r7RegenerableDerived
  ]
